### ISSUE TITLE
[BUG] 网站直接上传文件500报错

### ISSUE THREAD

**Issue by newcardriver** [1Panel-dev/1Panel#1104]
### 1Panel 版本

1.2.4

### 问题描述

面板搭建之后使用了HTTPS反代，在进行上传文件时报500。

### 重现步骤

左侧菜单 主机---->文件---->上传

![image](https://github.com/1Panel-dev/1Panel/assets/44741731/8739f13c-ca77-45e4-8a20-e754bbed115e)

### 期待的正确结果

上传成功

### 相关日志输出

```shell
[2023-05-22 17:57:42] [INFO] init logger successfully  
[2023-05-22 17:57:42] [INFO] init db successfully  
[2023-05-22 17:57:42] [INFO] Migration run successfully  
panic: Cannot acquire directory lock on "/opt/1panel/cache".  Another process is using this Badger database. error: resource temporarily unavailable

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/cache.Init()
	github.com/1Panel-dev/1Panel/backend/init/cache/cache.go:50 +0x17f
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:40 +0x8a
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func4(0x6d01080?, {0x31d5b41?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:21 +0x17
github.com/spf13/cobra.(*Command).execute(0x6d01080, {0xc0001121f0, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x6d01080)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	./main.go:23 +0x25
```

### 附加信息

不太清楚是不是由于反代的原因导致的，我上传的是一张很小的图片。

**Comment by zhengkunwang223** [comment]
直接通过端口访问上传文件报错吗？

**Comment by newcardriver** [comment]
> 直接通过端口访问上传文件报错吗？

直接使用端口访问上传文件不会报错，配置面板的反向代理是通过界面操作的，以下是部分配置，能麻烦帮忙看下吗？

![image](https://github.com/1Panel-dev/1Panel/assets/44741731/4bea2402-ec2e-4894-8138-b04c07b23167)
根据之前日志看，好像是访问到了后台服务，但是不知道为啥报错了。

ps：抹掉的是配置的面板后台二级域名。
