### ISSUE TITLE
编译安装1panel出现问题

### ISSUE THREAD

**Issue by dpkg123** [1Panel-dev/1Panel#1224]
### 请描述您的问题

由于内核不支持docker，遂执行编译安装
执行的步骤:
```
git clone https://github.com/1panel-dev/1panel
cd 1panel
make
```
log
```
Last login: Thu Jun  1 22:08:23 2023 from 127.0.0.1
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
user@localhost ~> cd 1panel/
user@localhost ~/1panel (dev)> make
cd /home/user/1panel/frontend && npm install && npm run build:dev
npm ERR! Invalid comparator: npm:esbuild-wasm@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2023-06-01T14_19_37_464Z-debug-0.log
make: *** [Makefile:15: build_frontend] エラー 1
user@localhost ~/1panel (dev) [2]>
```
单独执行npm install esbuild-wasm是没问题的:
```
user@localhost ~/1panel (dev) [2]> npm install esbuild-wasm

added 1 package in 11s
```

os : debian bookworm aarch64
kernel version: 4.19.157

**Comment by wanghe-fit2cloud** [comment]
Makefile 文件有提供相关指令：
```shell
make build_all
```

**Comment by dpkg123** [comment]
> Makefile 文件有提供相关指令：
> 
> ```shell
> make build_all
> ```
```
user@localhost ~/1panel (dev) [SIGINT]> make build_all
cd /home/user/1panel/frontend && npm install && npm run build:dev
npm WARN deprecated vscode-pug-languageservice@0.29.8: WARNING: This project has been renamed to @volar/pug-language-service. Install using @volar/pug-language-service instead.
npm WARN deprecated stringify-package@1.0.1: This module is not used anymore, and has been replaced by @npmcli/package-json
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated vscode-typescript-languageservice@0.29.8: WARNING: This project has been renamed to @volar/typescript-language-service. Install using @volar/typescript-language-service instead.
npm WARN deprecated vscode-vue-languageservice@0.29.8: WARNING: This project has been renamed to @volar/vue-language-service. Install using @volar/vue-language-service instead.
npm WARN deprecated @volar/html2pug@0.29.8: WARNING: This project has been renamed to @johnsoncodehk/html2pug. Install using @johnsoncodehk/html2pug instead.

added 931 packages, and audited 932 packages in 1m

152 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> panel@0.0.1 build:dev
> vite build --mode development

vite v2.9.15 building for development...
✓ 171 modules transformed.
✓ 187 modules transformed.
✓ 190 modules transformed.
✓ 191 modules transformed.
✓ 234 modules transformed.
✓ 3753 modules transformed.

(!) outDir /home/user/1panel/cmd/server/web is not inside project root and will not be emptied.
Use --emptyOutDir to override.

transforming (3758) node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js
<--- Last few GCs --->

[28762:0x5dd2b2f580]   247862 ms: Scavenge 2004.0 (2076.0) -> 2000.1 (2077.2) MB, 14.2 / 0.0 ms  (average mu = 0.752, current mu = 0.471) allocation failure;
[28762:0x5dd2b2f580]   247912 ms: Scavenge 2005.5 (2077.2) -> 2002.3 (2080.5) MB, 15.1 / 0.0 ms  (average mu = 0.752, current mu = 0.471) allocation failure;
[28762:0x5dd2b2f580]   248375 ms: Scavenge 2008.2 (2080.5) -> 2004.7 (2097.7) MB, 430.0 / 0.0 ms  (average mu = 0.752, current mu = 0.471) allocation failure;


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x71b77040dc node::Abort() [/lib/aarch64-linux-gnu/libnode.so.108]
 2: 0x71b761b918 void node::FPrintF<>(_IO_FILE*, char const*) [/lib/aarch64-linux-gnu/libnode.so.108]
 3: 0x71b7a37dbc v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib/aarch64-linux-gnu/libnode.so.108]
 4: 0x71b7a37f90 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib/aarch64-linux-gnu/libnode.so.108]
 5: 0x71b7bfe978  [/lib/aarch64-linux-gnu/libnode.so.108]
 6: 0x71b7c12628 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/lib/aarch64-linux-gnu/libnode.so.108]
 7: 0x71b7bf1304 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/lib/aarch64-linux-gnu/libnode.so.108]
 8: 0x71b7bf2530 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/lib/aarch64-linux-gnu/libnode.so.108]
 9: 0x71b7bd4c00 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/lib/aarch64-linux-gnu/libnode.so.108]
10: 0x71b7f7aee0 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/lib/aarch64-linux-gnu/libnode.so.108]
11: 0x71b7955bec  [/lib/aarch64-linux-gnu/libnode.so.108]
make: *** [Makefile:15: build_frontend] 中止
user@localhost ~/1panel (dev) [2]>
```

**Comment by zhengkunwang223** [comment]
参考这个 https://support.huaweicloud.com/codeci_faq/codeci_faq_1025.html

**Comment by dpkg123** [comment]
> 参考这个 https://support.huaweicloud.com/codeci_faq/codeci_faq_1025.html

```
go: downloading github.com/moby/spdystream v0.2.0
go: downloading github.com/prometheus/client_golang v1.14.0
go: downloading github.com/prometheus/client_model v0.3.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/prometheus/common v0.37.0
go: downloading github.com/prometheus/procfs v0.8.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
../cmd/server/web/web.go:8:12: pattern assets/*: no matching files found
make: *** [Makefile:18: build_backend_on_linux] エラー 1
```

**Comment by zhengkunwang223** [comment]
> > 参考这个 https://support.huaweicloud.com/codeci_faq/codeci_faq_1025.html
> 
> ```
> go: downloading github.com/moby/spdystream v0.2.0
> go: downloading github.com/prometheus/client_golang v1.14.0
> go: downloading github.com/prometheus/client_model v0.3.0
> go: downloading github.com/beorn7/perks v1.0.1
> go: downloading github.com/prometheus/common v0.37.0
> go: downloading github.com/prometheus/procfs v0.8.0
> go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
> ../cmd/server/web/web.go:8:12: pattern assets/*: no matching files found
> make: *** [Makefile:18: build_backend_on_linux] エラー 1
> ```

build_frontend 应该失败了 看一下原因

**Comment by dpkg123** [comment]
> > > 参考这个 https://support.huaweicloud.com/codeci_faq/codeci_faq_1025.html
> > 
> > 
> > ```
> > go: downloading github.com/moby/spdystream v0.2.0
> > go: downloading github.com/prometheus/client_golang v1.14.0
> > go: downloading github.com/prometheus/client_model v0.3.0
> > go: downloading github.com/beorn7/perks v1.0.1
> > go: downloading github.com/prometheus/common v0.37.0
> > go: downloading github.com/prometheus/procfs v0.8.0
> > go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
> > ../cmd/server/web/web.go:8:12: pattern assets/*: no matching files found
> > make: *** [Makefile:18: build_backend_on_linux] エラー 1
> > ```
> 
> build_frontend 应该失败了 看一下原因

怎么看

**Comment by zhengkunwang223** [comment]
> > > > 参考这个 https://support.huaweicloud.com/codeci_faq/codeci_faq_1025.html
> > > 
> > > 
> > > ```
> > > go: downloading github.com/moby/spdystream v0.2.0
> > > go: downloading github.com/prometheus/client_golang v1.14.0
> > > go: downloading github.com/prometheus/client_model v0.3.0
> > > go: downloading github.com/beorn7/perks v1.0.1
> > > go: downloading github.com/prometheus/common v0.37.0
> > > go: downloading github.com/prometheus/procfs v0.8.0
> > > go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
> > > ../cmd/server/web/web.go:8:12: pattern assets/*: no matching files found
> > > make: *** [Makefile:18: build_backend_on_linux] エラー 1
> > > ```
> > 
> > 
> > build_frontend 应该失败了 看一下原因
> 
> 怎么看

百度一下

**Comment by dpkg123** [comment]
> > > > > 参考这个 https://support.huaweicloud.com/codeci_faq/codeci_faq_1025.html
> > > > 
> > > > 
> > > > ```
> > > > go: downloading github.com/moby/spdystream v0.2.0
> > > > go: downloading github.com/prometheus/client_golang v1.14.0
> > > > go: downloading github.com/prometheus/client_model v0.3.0
> > > > go: downloading github.com/beorn7/perks v1.0.1
> > > > go: downloading github.com/prometheus/common v0.37.0
> > > > go: downloading github.com/prometheus/procfs v0.8.0
> > > > go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
> > > > ../cmd/server/web/web.go:8:12: pattern assets/*: no matching files found
> > > > make: *** [Makefile:18: build_backend_on_linux] エラー 1
> > > > ```
> > > 
> > > 
> > > build_frontend 应该失败了 看一下原因
> > 
> > 
> > 怎么看
> 
> 百度一下

~~百度了下，是缺少access/目录下的文件，但是克隆的目录没有这个文件。~~
~~已解决。但是cpu占用百分百正常吗？~~
```
user@localhost ~/1/build (dev)> sudo ./1panel
panic: error `BASE_DIR` find in /usr/bin/1pctl

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/viper.loadParams({0x2ee9b8a, 0x8})
        github.com/1Panel-dev/1Panel/backend/init/viper/viper.go:113 +0xf8
github.com/1Panel-dev/1Panel/backend/init/viper.Init()
        github.com/1Panel-dev/1Panel/backend/init/viper/viper.go:43 +0x25c
github.com/1Panel-dev/1Panel/backend/server.Start()
        github.com/1Panel-dev/1Panel/backend/server/server.go:33 +0x24
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func7(0x55a52e0?, {0x2edd087?, 0x0?, 0x0?})
        github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:21 +0x1c
github.com/spf13/cobra.(*Command).execute(0x55a52e0, {0x400004e210, 0x0, 0x0})
        github.com/spf13/cobra@v1.6.1/command.go:916 +0x5e0
github.com/spf13/cobra.(*Command).ExecuteC(0x55a52e0)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x368
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        ./main.go:23 +0x28
user@localhost ~/1/build (dev) [2]>
```

**Comment by zhengkunwang223** [comment]
https://github.com/1Panel-dev/installer 这个工程下有 1pctl 文件 
需要放在 /usr/bin下面

**Comment by dpkg123** [comment]
> https://github.com/1Panel-dev/installer 这个工程下有 1pctl 文件 需要放在 /usr/bin下面

ok
