### ISSUE TITLE
[BUG] 1Panel操作Docker容器后失败导致容器丢失

### ISSUE THREAD

**Issue by OrangeMas** [1Panel-dev/1Panel#1736]
### 1Panel 版本

v1.4.3

### 问题描述

1Panel操作Docker容器网络后失败导致容器丢失

### 重现步骤

- 前提：开放一个范围内的端口，但这个范围内有一个或多个端口占用。

1、新建一个容器，任何都可以。网络选择1Panel-network，端口全部开放
2、容器启动成功后编辑该容器，设置一段指定端口开放，提交后会提示端口占用。
然后刷新页面会发现刚才操作的容器丢失（数据也无）

### 相关日志输出

```shell
[2023-07-22 20:01:17] [INFO] init logger successfully  
[2023-07-22 20:01:18] [INFO] init db successfully  
[2023-07-22 20:01:18] [INFO] Migration run successfully  
[2023-07-22 20:01:18] [INFO] init cache successfully  
[2023-07-22 20:01:18] [INFO] init session successfully  
[2023-07-22 20:01:18] [INFO] sync app start...  
[2023-07-22 20:01:18] [INFO] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2023-07-22 20:01:25] [INFO] sync app successful  
[2023-07-22 20:01:25] [INFO] server run success on 42750 with http  
2023/07/22 20:01:25 583 :42750
[2023-07-22 20:03:35] [INFO] pull image stilleshan/frps successful!  
[2023-07-22 20:05:19] [INFO] new container info frps-server has been made, now start to create  
[2023-07-22 20:05:19] [INFO] create container frps-server successful! now check if the container is started and delete the container information if it is not.  
2023/07/22 20:11:28 583 Received SIGTERM.
2023/07/22 20:11:28 583 Waiting for connections to finish...
2023/07/22 20:11:28 583 Serve() returning...
[2023-07-22 20:11:28] [ERROR] accept tcp [::]:42750: use of closed network connection  
panic: accept tcp [::]:42750: use of closed network connection

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:58 +0x725
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func7(0x8352820?, {0x340f443?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:21 +0x17
github.com/spf13/cobra.(*Command).execute(0x8352820, {0xc000050240, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x8352820)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x406a59?)
	github.com/spf13/cobra@v1.6.1/command.go:968 +0x19
main.main()
	./main.go:23 +0x25
[2023-07-22 20:11:57] [INFO] init logger successfully  
[2023-07-22 20:11:57] [INFO] init db successfully  
[2023-07-22 20:11:57] [INFO] Migration run successfully  
[2023-07-22 20:11:57] [INFO] init cache successfully  
[2023-07-22 20:11:57] [INFO] init session successfully  
[2023-07-22 20:11:57] [INFO] no need to sync  
[2023-07-22 20:11:58] [INFO] server run success on 42750 with http
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
