### ISSUE TITLE
[BUG] 应用商店空白

### ISSUE THREAD

**Issue by chrisuhg** [1Panel-dev/1Panel#2234]
### 联系方式

chris.hg@qq.com

### 1Panel 版本

v1.5.5

### 问题描述

应用商店列表空白，获取不到任何应用，但应用列表提示已经为最新

### 重现步骤

未能修复，安装后做过的改变只有 IP 地址变更。、
网络环境没有改变，相同网络环境下其他设备可以访问 https://apps-assets.fit2cloud.com/stable/1panel.json.zip 

重启1penal未能解决问题，未尝试重启设备。

### 期待的正确结果

- 获取到正确的应用商店列表
- 当无法获取应用列表或者列表空白时对用户提示错误

### 相关日志输出

```
[2023-09-08 15:25:48] [INFO] init logger successfully  
[2023-09-08 15:25:52] [INFO] init db successfully  
[2023-09-08 15:25:58] [INFO] Migration run successfully  
[2023-09-08 15:25:58] [INFO] init cache successfully  
[2023-09-08 15:25:58] [INFO] init session successfully  
[2023-09-08 15:26:02] [INFO] sync app start...  
[2023-09-08 15:26:03] [INFO] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2023-09-08 15:24:53] [INFO] init logger successfully  
[2023-09-08 15:25:03] [INFO] init db successfully  
[2023-09-08 15:25:03] [INFO] Migration run successfully  
[2023-09-08 15:25:03] [INFO] init cache successfully  
[2023-09-08 15:25:03] [INFO] init session successfully  
[2023-09-08 15:25:06] [INFO] no need to sync  
[2023-09-08 15:25:06] [INFO] server run success on 33930 with http  
2023/09/08 15:25:06 548 :33930
[2023-09-08 16:17:19] [INFO] init logger successfully  
[2023-09-08 16:17:33] [INFO] init db successfully  
[2023-09-08 16:17:33] [INFO] Migration run successfully  
[2023-09-08 16:17:33] [INFO] init cache successfully  
[2023-09-08 16:17:33] [INFO] init session successfully  
[2023-09-08 16:17:36] [INFO] no need to sync  
[2023-09-08 16:17:37] [INFO] server run success on 33930 with http  
2023/09/08 16:17:37 563 :33930
2023/09/08 17:08:04 563 Received SIGTERM.
2023/09/08 17:08:04 563 Waiting for connections to finish...
2023/09/08 17:08:04 563 Serve() returning...
2023/09/08 17:08:04 563 [::]:33930 Listener closed.
[2023-09-08 17:08:05] [ERROR] accept tcp [::]:33930: use of closed network connection  
panic: accept tcp [::]:33930: use of closed network connection

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:59 +0x638
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func7(0x654df80?, {0x1ee8db2?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x1c
github.com/spf13/cobra.(*Command).execute(0x654df80, {0x400010a200, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x654df80)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(0x400006c768?)
	github.com/spf13/cobra@v1.6.1/command.go:968 +0x1c
main.main()
	./main.go:23 +0x24
[2023-09-08 17:08:33] [INFO] init logger successfully  
[2023-09-08 17:08:44] [INFO] init db successfully  
[2023-09-08 17:08:44] [INFO] Migration run successfully  
[2023-09-08 17:08:44] [INFO] init cache successfully  
[2023-09-08 17:08:44] [INFO] init session successfully  
[2023-09-08 17:08:47] [INFO] no need to sync  
[2023-09-08 17:08:47] [INFO] server run success on 33930 with http  
2023/09/08 17:08:47 548 :33930
2023/09/08 17:16:16 548 Received SIGTERM.
2023/09/08 17:16:16 548 Waiting for connections to finish...
2023/09/08 17:16:16 548 Serve() returning...
[2023-09-08 17:16:16] [ERROR] accept tcp [::]:33930: use of closed network connection  
panic: accept tcp [::]:33930: use of closed network connection

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:59 +0x638
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func7(0x654df80?, {0x1ee8db2?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x1c
github.com/spf13/cobra.(*Command).execute(0x654df80, {0x400004c240, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x654df80)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(0x400006c768?)
	github.com/spf13/cobra@v1.6.1/command.go:968 +0x1c
main.main()
	./main.go:23 +0x24
[2023-09-08 17:16:17] [INFO] init logger successfully  
[2023-09-08 17:16:17] [INFO] init db successfully  
[2023-09-08 17:16:17] [INFO] Migration run successfully  
[2023-09-08 17:16:17] [INFO] init cache successfully  
[2023-09-08 17:16:17] [INFO] init session successfully  
[2023-09-08 17:16:20] [INFO] no need to sync  
[2023-09-08 17:16:20] [INFO] server run success on 33930 with http  
2023/09/08 17:16:20 2006 :33930
[2023-09-08 17:17:52] [INFO] start sync local apps...  
[2023-09-08 17:17:52] [INFO] sync local apps success  
[2023-09-08 17:17:55] [INFO] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
2023/09/08 17:24:50 2006 Received SIGTERM.
2023/09/08 17:24:50 2006 Waiting for connections to finish...
2023/09/08 17:24:50 2006 Serve() returning...
[2023-09-08 17:24:50] [ERROR] accept tcp [::]:33930: use of closed network connection  
panic: accept tcp [::]:33930: use of closed network connection

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:59 +0x638
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func7(0x654df80?, {0x1ee8db2?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x1c
github.com/spf13/cobra.(*Command).execute(0x654df80, {0x400004c240, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x654df80)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(0x400006c768?)
	github.com/spf13/cobra@v1.6.1/command.go:968 +0x1c
main.main()
	./main.go:23 +0x24
[2023-09-08 17:24:51] [INFO] init logger successfully  
[2023-09-08 17:24:51] [INFO] init db successfully  
[2023-09-08 17:24:51] [INFO] Migration run successfully  
[2023-09-08 17:24:51] [INFO] init cache successfully  
[2023-09-08 17:24:51] [INFO] init session successfully  
[2023-09-08 17:24:54] [INFO] no need to sync  
[2023-09-08 17:24:54] [INFO] server run success on 33930 with http  
2023/09/08 17:24:54 2386 :33930
[2023-09-08 17:27:11] [INFO] start sync local apps...  
[2023-09-08 17:27:11] [INFO] sync local apps success  
[2023-09-08 17:27:12] [INFO] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
```

**Comment by wanghe-fit2cloud** [comment]
1Panel 系统资源统一放在阿里 OSS，是全球加速的 cdn，应该不会慢，除非 cdn 节点有问题了。

**Comment by yggcwx** [comment]
我也重现了这个问题，期望 1Panel官方能正视此问题，尽快解决
