### ISSUE TITLE
[BUG] 系统升级失败  SQLITE_BUSY   1.5.2升级到1.5.5

### ISSUE THREAD

**Issue by wxydejoy** [1Panel-dev/1Panel#2263]
### 1Panel 版本

1.5.2

### 问题描述

https://bbs.fit2cloud.com/t/topic/1387/5

### 重现步骤

尝试过程如下
重启1pcl  后升级  无效
重启服务器 后升级 无效
停止服务后手动下载二进制文件 替换成功但版本显示还是1.5.2 

### 相关日志输出

```shell
[2023-09-12 00:00:00] [INFO] AppStore scheduled task in progress ...  
[2023-09-12 00:00:00] [INFO] Website scheduled task in progress ...  
[2023-09-12 00:00:00] [INFO] Website scheduled task has completed  
[2023-09-12 00:00:00] [INFO] The scheduled certificate update task is currently in progress ...  
[2023-09-12 00:00:00] [INFO] The scheduled certificate update task has completed  
[2023-09-12 00:00:20] [INFO] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2023-09-12 00:00:25] [INFO] AppStore scheduled task has completed  
[2023-09-12 09:45:47] [INFO] start to upgrade now...  
[2023-09-12 09:45:50] [INFO] download all file successful!  
[2023-09-12 09:45:50] [DEBUG] tar zxvfC /opt/1panel/tmp/upgrade/upgrade_20230912094547/downloads/1panel-v1.5.5-linux-arm64.tar.gz /opt/1panel/tmp/upgrade/upgrade_20230912094547/downloads  
[2023-09-12 09:46:23] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 09:46:25] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 09:47:32] [INFO] backup original data successful, now start to upgrade!  
[2023-09-12 09:47:44] [ERROR] Insert basic monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 09:48:45] [ERROR] Insert io monitoring data failed, err: database disk image is malformed (11)  
[2023-09-12 09:48:45] [ERROR] Insert network monitoring data failed, err: database disk image is malformed (11)  
[2023-09-12 09:50:04] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 09:50:10] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 09:50:11] [ERROR] rollback 1panel failed, err:   
[2023-09-12 09:51:14] [ERROR] rollback 1pctl failed, err:   
[2023-09-12 09:51:14] [ERROR] upgrade 1panel failed, err:   
[2023-09-12 09:51:16] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 09:51:27] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 09:51:27] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 09:54:23] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 09:54:23] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 12:27:12] [ERROR] accept tcp [::]:11198: use of closed network connection  
[2023-09-12 12:27:14] [INFO] init logger successfully  
[2023-09-12 12:27:14] [INFO] init db successfully  
[2023-09-12 12:27:14] [INFO] Migration run successfully  
[2023-09-12 12:27:14] [INFO] init cache successfully  
[2023-09-12 12:27:14] [INFO] init session successfully  
[2023-09-12 12:27:19] [INFO] no need to sync  
[2023-09-12 12:27:19] [INFO] server run success on 11198 with http  
2023/09/12 12:27:19 689572 :11198
[2023-09-12 12:56:15] [INFO] new container info 1Panel-bitwarden-5W2Z has been update, now start to recreate  
[2023-09-12 12:56:18] [INFO] update container 1Panel-bitwarden-5W2Z successful! now check if the container is started.  
[2023-09-12 13:10:44] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 13:10:44] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 13:15:20] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 13:15:20] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 13:15:49] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 13:15:55] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 13:16:30] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 13:17:46] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 13:17:46] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 13:18:37] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 13:18:41] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 13:41:27] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 13:41:27] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
2023/09/12 14:00:02 689572 Received SIGTERM.
2023/09/12 14:00:02 689572 Waiting for connections to finish...
2023/09/12 14:00:02 689572 Serve() returning...
2023/09/12 14:00:02 689572 [::]:11198 Listener closed.
[2023-09-12 14:00:02] [ERROR] accept tcp [::]:11198: use of closed network connection  
panic: accept tcp [::]:11198: use of closed network connection

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:59 +0x638
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func7(0x654df80?, {0x1ee8d12?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:21 +0x1c
github.com/spf13/cobra.(*Command).execute(0x654df80, {0x400011e220, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x654df80)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(0x400006c768?)
	github.com/spf13/cobra@v1.6.1/command.go:968 +0x1c
main.main()
	./main.go:23 +0x24
[2023-09-12 14:00:31] [INFO] init logger successfully  
[2023-09-12 14:00:31] [INFO] init db successfully  
[2023-09-12 14:00:31] [INFO] Migration run successfully  
[2023-09-12 14:00:31] [INFO] init cache successfully  
[2023-09-12 14:00:31] [INFO] init session successfully  
[2023-09-12 14:05:19] [INFO] init logger successfully  
[2023-09-12 14:05:19] [INFO] init db successfully  
[2023-09-12 14:05:19] [INFO] Migration run successfully  
[2023-09-12 14:05:19] [INFO] init cache successfully  
[2023-09-12 14:05:19] [INFO] init session successfully  
[2023-09-12 14:05:26] [INFO] no need to sync  
[2023-09-12 14:05:26] [INFO] server run success on 11198 with http  
2023/09/12 14:05:26 695104 :11198
[2023-09-12 14:07:59] [INFO] start to upgrade now...  
[2023-09-12 14:08:04] [INFO] download all file successful!  
[2023-09-12 14:08:05] [DEBUG] tar zxvfC /opt/1panel/tmp/upgrade/upgrade_20230912140759/downloads/1panel-v1.5.5-linux-arm64.tar.gz /opt/1panel/tmp/upgrade/upgrade_20230912140759/downloads  
[2023-09-12 14:08:39] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:09:48] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:09:49] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:10:21] [ERROR] Insert basic monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:10:39] [ERROR] Insert basic monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:10:44] [INFO] backup original data successful, now start to upgrade!  
[2023-09-12 14:11:32] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:11:43] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:11:43] [ERROR] Insert basic monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:11:48] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:11:48] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:12:35] [ERROR] Insert basic monitoring data failed, err: database disk image is malformed (11)  
[2023-09-12 14:12:43] [ERROR] Insert network monitoring data failed, err: database disk image is malformed (11)  
[2023-09-12 14:12:43] [ERROR] Insert io monitoring data failed, err: database disk image is malformed (11)  
[2023-09-12 14:13:16] [ERROR] rollback 1panel failed, err:   
[2023-09-12 14:14:54] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:15:11] [ERROR] rollback 1pctl failed, err:   
[2023-09-12 14:15:11] [ERROR] upgrade 1panel failed, err:   
2023/09/12 14:16:56 695104 Received SIGTERM.
2023/09/12 14:16:56 695104 Waiting for connections to finish...
2023/09/12 14:16:56 695104 Serve() returning...
2023/09/12 14:16:56 695104 [::]:11198 Listener closed.
[2023-09-12 14:16:56] [ERROR] accept tcp [::]:11198: use of closed network connection  
panic: accept tcp [::]:11198: use of closed network connection

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:59 +0x638
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func7(0x654df80?, {0x1ee8db2?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x1c
github.com/spf13/cobra.(*Command).execute(0x654df80, {0x400004c240, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x654df80)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(0x400006c768?)
	github.com/spf13/cobra@v1.6.1/command.go:968 +0x1c
main.main()
	./main.go:23 +0x24
[2023-09-12 14:17:07] [INFO] init logger successfully  
[2023-09-12 14:17:07] [INFO] init db successfully  
[2023-09-12 14:17:07] [INFO] Migration run successfully  
[2023-09-12 14:17:08] [INFO] init cache successfully  
[2023-09-12 14:17:08] [INFO] init session successfully  
[2023-09-12 14:17:12] [INFO] no need to sync  
[2023-09-12 14:17:12] [INFO] server run success on 11198 with http  
2023/09/12 14:17:12 695925 :11198
2023/09/12 14:17:44 695925 Received SIGTERM.
2023/09/12 14:17:44 695925 Waiting for connections to finish...
2023/09/12 14:17:44 695925 Serve() returning...
[2023-09-12 14:17:44] [ERROR] accept tcp [::]:11198: use of closed network connection  
2023/09/12 14:17:44 695925 [::]:11198 Listener closed.
panic: accept tcp [::]:11198: use of closed network connection

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:59 +0x638
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func7(0x654df80?, {0x1ee8db2?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x1c
github.com/spf13/cobra.(*Command).execute(0x654df80, {0x400011a200, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x654df80)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(0x400006c768?)
	github.com/spf13/cobra@v1.6.1/command.go:968 +0x1c
main.main()
	./main.go:23 +0x24
[2023-09-12 14:17:51] [INFO] init logger successfully  
[2023-09-12 14:17:51] [INFO] init db successfully  
[2023-09-12 14:17:51] [INFO] Migration run successfully  
[2023-09-12 14:17:51] [INFO] init cache successfully  
[2023-09-12 14:17:51] [INFO] init session successfully  
[2023-09-12 14:28:43] [INFO] init logger successfully  
[2023-09-12 14:28:43] [INFO] init db successfully  
[2023-09-12 14:28:43] [INFO] Migration run successfully  
[2023-09-12 14:28:43] [INFO] init cache successfully  
[2023-09-12 14:28:43] [INFO] init session successfully  
[2023-09-12 14:28:48] [INFO] no need to sync  
[2023-09-12 14:28:48] [INFO] server run success on 11198 with http  
2023/09/12 14:28:48 697160 :11198
[2023-09-12 14:31:56] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:31:56] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:33:49] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:34:06] [ERROR] Insert basic monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:35:11] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:35:20] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:59:08] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 14:59:08] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 15:02:29] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 15:02:31] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 15:05:13] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 15:05:13] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 15:07:16] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 15:07:16] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 15:09:13] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 15:09:13] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 15:10:56] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 15:29:02] [ERROR] Insert network monitoring data failed, err: database is locked (5) (SQLITE_BUSY)  
[2023-09-12 15:29:02] [ERROR] Insert io monitoring data failed, err: database is locked (5) (SQLITE_BUSY)
```

**Comment by wxydejoy** [comment]
环境  debian11 rk3328 1G内存

**Comment by wanghe-fit2cloud** [comment]
可以参考这篇文章：https://bbs.fit2cloud.com/t/topic/1387/7
> 与服务器小内存也有关系。
