### ISSUE TITLE
[BUG]新建网站运行环境失败目录不存在

### ISSUE THREAD

**Issue by gitzaai** [1Panel-dev/1Panel#2628]
### 1Panel 版本

v1.7.2

### 问题描述

新建网站选择运行环境时：

看到创建容器失败。

尝试方法：重启服务器、重启docker、重启

服务器配置：

发行版本 debian-11.8
内核版本 5.10.0-26-cloud-amd64
系统类型 x86_64

### 重现步骤

新建网站选择运行环境时：

### 相关日志输出

```shell
goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:59 +0x7a5
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func8(0x6dd11a0?, {0x25e2a5f?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x17
github.com/spf13/cobra.(*Command).execute(0x6dd11a0, {0xc00010a200, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x6dd11a0)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x4069d9?)
	github.com/spf13/cobra@v1.6.1/command.go:968 +0x19
main.main()
	./main.go:23 +0x25
[2023-10-22 21:43:14] [INFO] init logger successfully  
[2023-10-22 21:43:21] [INFO] init db successfully  
[2023-10-22 21:43:21] [INFO] Migration run successfully  
[2023-10-22 21:43:21] [INFO] init cache successfully  
[2023-10-22 21:43:21] [INFO] init session successfully  
[2023-10-22 21:43:26] [INFO] Starting synchronization with App Store...  
[2023-10-22 21:43:26] [INFO] server run success on 32909 with http  
2023/10/22 21:43:26 471 :32909
[2023-10-22 21:43:26] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2023-10-22 21:43:27] [INFO] The App Store is at the latest version  
2023/10/22 22:09:18 471 Received SIGTERM.
2023/10/22 22:09:18 471 Waiting for connections to finish...
2023/10/22 22:09:18 471 Serve() returning...
[2023-10-22 22:09:18] [ERROR] accept tcp [::]:32909: use of closed network connection  
panic: accept tcp [::]:32909: use of closed network connection

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:59 +0x7a5
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func8(0x6dd11a0?, {0x25e2a5f?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x17
github.com/spf13/cobra.(*Command).execute(0x6dd11a0, {0xc000050250, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x6dd11a0)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x4069d9?)
	github.com/spf13/cobra@v1.6.1/command.go:968 +0x19
main.main()
	./main.go:23 +0x25
[2023-10-22 22:09:27] [INFO] init logger successfully  
[2023-10-22 22:09:33] [INFO] init db successfully  
[2023-10-22 22:09:33] [INFO] Migration run successfully  
[2023-10-22 22:09:33] [INFO] init cache successfully  
[2023-10-22 22:09:33] [INFO] init session successfully  
[2023-10-22 22:09:37] [INFO] Starting synchronization with App Store...  
[2023-10-22 22:09:37] [INFO] server run success on 32909 with http  
2023/10/22 22:09:37 469 :32909
[2023-10-22 22:09:37] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2023-10-22 22:09:38] [INFO] The App Store is at the latest version  
[2023-10-22 22:31:04] [INFO] delete app php8-cfaa2site backups successful  
[2023-10-22 22:32:14] [INFO] download app[PHP 8] from https://apps-assets.fit2cloud.com/stable/1panel/php8/8.2.5/php8-8.2.5.tar.gz  
[2023-10-22 22:32:15] [ERROR] download app[PHP 8] error 文件不存在  
[2023-10-22 22:33:38] [ERROR] reading webSocket message failed, err: websocket: close 1005 (no status)  
[2023-10-22 22:33:38] [DEBUG] thread of receive ws msg has exited now  
[2023-10-22 22:33:38] [INFO] websocket finished  
[2023-10-22 22:33:38] [ERROR] ssh session wait failed, err: signal: killed  
[2023-10-22 22:33:38] [DEBUG] thread of handle slave event has exited now  
[2023-10-22 22:34:00] [INFO] delete app php8-cfaa2site backups successful  
[2023-10-22 22:34:25] [INFO] create database flarum_er44f2 successful!  
[2023-10-22 22:34:25] [INFO] download app[Flarum] from https://apps-assets.fit2cloud.com/stable/1panel/flarum/1.8.0/flarum-1.8.0.tar.gz  
[2023-10-22 22:44:19] [ERROR] reading webSocket message failed, err: websocket: close 1005 (no status)  
[2023-10-22 22:44:19] [DEBUG] thread of receive ws msg has exited now  
[2023-10-22 22:44:19] [INFO] websocket finished  
[2023-10-22 22:44:19] [ERROR] ssh session wait failed, err: signal: killed  
[2023-10-22 22:44:19] [DEBUG] thread of handle slave event has exited now  
[2023-10-22 22:54:24] [ERROR] reading webSocket message failed, err: websocket: close 1005 (no status)  
[2023-10-22 22:54:24] [DEBUG] thread of receive ws msg has exited now  
[2023-10-22 22:54:24] [INFO] websocket finished  
[2023-10-22 22:54:24] [ERROR] ssh session wait failed, err: signal: killed  
[2023-10-22 22:54:24] [DEBUG] thread of handle slave event has exited now  
[2023-10-22 23:01:56] [INFO] execute delete database sql successful, now start to drop uploads and records  
[2023-10-22 23:01:56] [INFO] delete database mysql5-flarum_er44f2 backups successful  
[2023-10-22 23:01:56] [INFO] delete app flarum-flarum backups successful  
[2023-10-22 23:04:35] [INFO] download app[PHP 8] from https://apps-assets.fit2cloud.com/stable/1panel/php8/8.2.5/php8-8.2.5.tar.gz  
[2023-10-22 23:04:36] [ERROR] download app[PHP 8] error 文件不存在  
[2023-10-22 23:07:56] [INFO] delete app php8-cfaa2site backups successful  
[2023-10-22 23:08:57] [INFO] download app[PHP 8] from https://apps-assets.fit2cloud.com/stable/1panel/php8/8.2.5/php8-8.2.5.tar.gz  
[2023-10-22 23:08:57] [ERROR] download app[PHP 8] error 文件不存在
```

### 附加信息

![Snipaste_2023-10-22_22-33-09.jpg](https://cdnjson.com/images/2023/10/22/Snipaste_2023-10-22_22-33-09.jpg)

**Comment by wanghe-fit2cloud** [comment]
进入应用商店列表，点击右上角的 `更新应用列表` 按钮，等待同步成功后再来尝试一下，如下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/9549bd8e-32c3-4318-87b2-b87b239f5e5a)

**Comment by gitzaai** [comment]
按照你的方法还是不行，更新到1.7.3创建也是不行。
我选择新建一个php环境，就能创建成功。

![Snipaste_2023-10-23_21-16-35.jpg](https://cdnjson.com/images/2023/10/23/Snipaste_2023-10-23_21-16-35.jpg)

**Comment by wanghe-fit2cloud** [comment]
应用商店中 PHP 版本已更新，就是要更新操作后新建最新版本。

**Comment by qingweiSun** [comment]
node 的呢。没提示需要更新
