### ISSUE TITLE
[BUG] 快照迁移失败

### ISSUE THREAD

**Issue by r1172464137** [1Panel-dev/1Panel#2976]
### 1Panel 版本

v1.8.2

### 问题描述

快照从v1.8.2迁移到另一台v1.8.2失败

### 重现步骤

如上

### 相关日志输出

```shell
[2023-11-16 06:48:24] [INFO] init logger successfully  
[2023-11-16 06:48:24] [INFO] init db successfully  
[2023-11-16 06:48:25] [INFO] Migration run successfully  
[2023-11-16 06:48:25] [INFO] init cache successfully  
[2023-11-16 06:48:25] [INFO] init session successfully  
[2023-11-16 06:48:25] [DEBUG] synchronize system time with [pool.ntp.org] successful!  
[2023-11-16 06:48:28] [INFO] Starting synchronization with App Store...  
[2023-11-16 06:48:30] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2023-11-16 06:48:31] [INFO] Starting synchronization of application details...  
[2023-11-16 06:48:58] [INFO] Synchronization of application details Success  
[2023-11-16 06:48:58] [INFO] Synchronization with the App Store was successful!  
[2023-11-16 06:57:41] [INFO] init logger successfully  
[2023-11-16 06:57:47] [INFO] init db successfully  
[2023-11-16 06:57:47] [INFO] Migration run successfully  
[2023-11-16 06:57:47] [INFO] init cache successfully  
[2023-11-16 06:57:47] [INFO] init session successfully  
[2023-11-16 06:57:48] [DEBUG] synchronize system time with [pool.ntp.org] successful!  
[2023-11-16 06:57:52] [INFO] Starting synchronization with App Store...  
[2023-11-16 06:57:55] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
                                                                      [2023-11-16 08:51:08] [INFO] init logger successfully  
[2023-11-16 08:51:12] [INFO] init db successfully  
[2023-11-16 08:51:12] [INFO] Migration run successfully  
[2023-11-16 08:51:12] [INFO] init cache successfully  
[2023-11-16 08:51:12] [INFO] init session successfully  
[2023-11-16 08:51:13] [DEBUG] synchronize system time with [pool.ntp.org] successful!  
[2023-11-16 08:51:16] [INFO] Starting synchronization with App Store...  
[2023-11-16 08:51:18] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2023-11-16 08:51:21] [INFO] The App Store is at the latest version  
[2023-11-16 08:53:04] [INFO] start to recover panel by snapshot now  
[2023-11-16 08:54:14] [DEBUG] tar zxvfC /opt/1panel/tmp/system/1panel_v1.8.2_20231116150413/1panel_v1.8.2_20231116150413.tar.gz /opt/1panel/tmp/system/1panel_v1.8.2_20231116150413  
[2023-11-16 08:54:35] [INFO] handle docker data successful!  
[2023-11-16 08:58:02] [INFO] handle docker data successful!  
[2023-11-16 08:58:02] [INFO] handle docker daemon.json successful!  
[2023-11-16 08:58:09] [DEBUG] \cp -f /usr/local/bin/1panel /opt/1panel_original/original_1panel_v1.8.2_20231116150413/1panel  
[2023-11-16 08:58:09] [DEBUG] \cp -f /opt/1panel/tmp/system/1panel_v1.8.2_20231116150413/1panel_v1.8.2_20231116150413/1panel/1panel /usr/local/bin/1panel  
[2023-11-16 08:58:10] [INFO] handle binary panel successful!  
[2023-11-16 08:58:10] [DEBUG] \cp -f /usr/local/bin/1pctl /opt/1panel_original/original_1panel_v1.8.2_20231116150413/1pctl  
[2023-11-16 08:58:10] [DEBUG] \cp -f /opt/1panel/tmp/system/1panel_v1.8.2_20231116150413/1panel_v1.8.2_20231116150413/1panel/1pctl /usr/local/bin/1pctl  
[2023-11-16 08:58:10] [INFO] handle binary 1pactl successful!  
[2023-11-16 08:58:10] [DEBUG] \cp -f /etc/systemd/system/1panel.service /opt/1panel_original/original_1panel_v1.8.2_20231116150413/1panel.service  
[2023-11-16 08:58:10] [DEBUG] \cp -f /opt/1panel/tmp/system/1panel_v1.8.2_20231116150413/1panel_v1.8.2_20231116150413/1panel/1panel.service /etc/systemd/system/1panel.service  
[2023-11-16 08:58:10] [INFO] handle panel service successful!  
[2023-11-16 08:58:10] [DEBUG] tar --warning=no-file-changed --ignore-failed-read -zcf /opt/1panel_original/original_1panel_v1.8.2_20231116150413/1panel_backup.tar.gz  --exclude ./system --exclude *.sock -C /opt/1panel/backup .  
[2023-11-16 08:58:10] [DEBUG] tar -zxf /opt/1panel/tmp/system/1panel_v1.8.2_20231116150413/1panel_v1.8.2_20231116150413/1panel/1panel_backup.tar.gz -C /opt/1panel/backup .  
[2023-11-16 08:58:10] [INFO] handle backup data successful!  
[2023-11-16 08:58:10] [DEBUG] tar --warning=no-file-changed --ignore-failed-read -zcf /opt/1panel_original/original_1panel_v1.8.2_20231116150413/1panel_data.tar.gz  --exclude ./tmp --exclude ./log --exclude ./cache --exclude ./backup --exclude *.sock -C /opt/1panel .  
[2023-11-16 08:58:10] [DEBUG] tar -zxf /opt/1panel/tmp/system/1panel_v1.8.2_20231116150413/1panel_v1.8.2_20231116150413/1panel/1panel_data.tar.gz -C /opt/1panel .  
[2023-11-16 08:58:33] [DEBUG] start to rebuild all app  
[2023-11-16 08:58:33] [ERROR] get all app installed for rebuild failed, err: database disk image is malformed (11)  
[2023-11-16 08:58:33] [INFO] recover successful  
[2023-11-16 08:58:35] [INFO] init logger successfully  
[2023-11-16 08:58:35] [INFO] init db successfully  
[2023-11-16 08:58:35] [ERROR] database disk image is malformed (11)  
panic: database disk image is malformed (11)

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/migration.Init()
	github.com/1Panel-dev/1Panel/backend/init/migration/migrate.go:58 +0x753
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:37 +0x45
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func10(0x6e21ac0?, {0x261840e?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x17
github.com/spf13/cobra.(*Command).execute(0x6e21ac0, {0xc00010c200, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x6e21ac0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x4069d9?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
	./main.go:23 +0x25
[2023-11-16 08:58:40] [INFO] init logger successfully  
[2023-11-16 08:58:40] [INFO] init db successfully  
[2023-11-16 08:58:40] [ERROR] database disk image is malformed (11)  
panic: database disk image is malformed (11)

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/migration.Init()
	github.com/1Panel-dev/1Panel/backend/init/migration/migrate.go:58 +0x753
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:37 +0x45
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func10(0x6e21ac0?, {0x261840e?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x17
github.com/spf13/cobra.(*Command).execute(0x6e21ac0, {0xc000050250, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x6e21ac0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x4069d9?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
	./main.go:23 +0x25
[2023-11-16 08:58:46] [INFO] init logger successfully  
[2023-11-16 08:58:46] [INFO] init db successfully  
[2023-11-16 08:58:46] [ERROR] database disk image is malformed (11)  
panic: database disk image is malformed (11)

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/migration.Init()
	github.com/1Panel-dev/1Panel/backend/init/migration/migrate.go:58 +0x753
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:37 +0x45
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func10(0x6e21ac0?, {0x261840e?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x17
github.com/spf13/cobra.(*Command).execute(0x6e21ac0, {0xc00010a200, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x6e21ac0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x4069d9?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
	./main.go:23 +0x25
[2023-11-16 08:58:51] [INFO] init logger successfully  
[2023-11-16 08:58:51] [INFO] init db successfully  
[2023-11-16 08:58:51] [ERROR] database disk image is malformed (11)  
panic: database disk image is malformed (11)

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/migration.Init()
	github.com/1Panel-dev/1Panel/backend/init/migration/migrate.go:58 +0x753
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:37 +0x45
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func10(0x6e21ac0?, {0x261840e?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x17
github.com/spf13/cobra.(*Command).execute(0x6e21ac0, {0xc00010a200, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x6e21ac0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x4069d9?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
	./main.go:23 +0x25
[2023-11-16 08:58:57] [INFO] init logger successfully  
[2023-11-16 08:58:57] [INFO] init db successfully  
[2023-11-16 08:58:57] [ERROR] database disk image is malformed (11)  
panic: database disk image is malformed (11)

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/migration.Init()
	github.com/1Panel-dev/1Panel/backend/init/migration/migrate.go:58 +0x753
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:37 +0x45
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func10(0x6e21ac0?, {0x261840e?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x17
github.com/spf13/cobra.(*Command).execute(0x6e21ac0, {0xc000050250, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x6e21ac0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x4069d9?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
	./main.go:23 +0x25
```

**Comment by r1172464137** [comment]
顺便说下，刚才在一台1.8.2的机器上使用了1.8.0的备份是没问题的

**Comment by ssongliu** [comment]
感谢反馈，这里错误信息的意思是数据库文件，可以暂时先直接将数据库文件(/opt/1panel/db/1Panel.db)手动复制过去后重启，我们再找一下其他的解决办法。

**Comment by ssongliu** [comment]
重复 #2958
