### ISSUE TITLE
[BUG]面板关闭SSL后无法登录面板

### ISSUE THREAD

**Issue by 60999** [1Panel-dev/1Panel#3223]
### 1Panel 版本

v1.8.5

### 问题描述

[BUG]面板关闭SSL后无法登录面板

### 重现步骤

不知道能否复现，当时环境如下：
（因无法通过DNSPOD-API成功申请证书）手动上传a.bbb.ccc域名证书，给面板SSL使用，此处简写为手动证书；
因无法续签该证书，在证书管理中用HTTP方式申请了a.bbb.ccc域名证书，此处简写为HTTP证书；
以上a.bbb.ccc域名都是同一个域名
在证书管理中删除手动证书失败，当前面板在用这个证书；
再面板设置中关掉SSL，提示重启。
后面完蛋，无法登录。

### 期待的正确结果

无证书也可https登录面板

### 相关日志输出

```shell
[2023-12-07 00:00:00] [INFO] AppStore scheduled task in progress ...  
[2023-12-07 00:00:00] [INFO] Starting synchronization with App Store...  
[2023-12-07 00:00:00] [INFO] The scheduled certificate update task is currently in progress ...  
[2023-12-07 00:00:00] [INFO] The scheduled certificate update task has completed  
[2023-12-07 00:00:00] [INFO] Website scheduled task in progress ...  
[2023-12-07 00:00:00] [INFO] Website scheduled task has completed  
[2023-12-07 00:00:00] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2023-12-07 00:00:00] [INFO] The App Store is at the latest version  
[2023-12-07 00:00:00] [INFO] AppStore scheduled task has completed  
[2023-12-07 01:40:00] [INFO] start to backup website 备份网站 to LOCAL  
[2023-12-07 01:40:00] [INFO] put website.json into tmp dir successful  
[2023-12-07 01:40:00] [INFO] put openresty conf into tmp dir successful  
[2023-12-07 01:40:00] [DEBUG] tar --warning=no-file-changed --ignore-failed-read -zcf /opt/1panel/backup/website/a.abc.dd/website_a.abc.dd_20231207014000/a.abc.dd.web.tar.gz  --exclude *.sock -C /opt/1panel/apps/openresty/openresty/www/sites a.abc.dd  
[2023-12-07 01:40:00] [INFO] put web.tar.gz into tmp dir successful, now start to tar tmp dir  
[2023-12-07 01:40:00] [DEBUG] tar --warning=no-file-changed --ignore-failed-read -zcf /opt/1panel/backup/website/a.abc.dd/website_a.abc.dd_20231207014000.tar.gz  --exclude *.sock -C /opt/1panel/backup/website/a.abc.dd website_a.abc.dd_20231207014000  
[2023-12-07 01:40:00] [INFO] put website.json into tmp dir successful  
[2023-12-07 01:40:00] [INFO] put openresty conf into tmp dir successful  
[2023-12-07 01:40:00] [DEBUG] tar --warning=no-file-changed --ignore-failed-read -zcf /opt/1panel/backup/website/y8.ink/website_y8.ink_20231207014000/y8.ink.web.tar.gz  --exclude *.sock -C /opt/1panel/apps/openresty/openresty/www/sites dd.eee 
[2023-12-07 01:40:00] [INFO] put web.tar.gz into tmp dir successful, now start to tar tmp dir  
[2023-12-07 01:40:00] [DEBUG] tar --warning=no-file-changed --ignore-failed-read -zcf /opt/1panel/backup/website/y8.ink/website_y8.ink_20231207014000.tar.gz  --exclude *.sock -C /opt/1panel/backup/website/dd.eeewebsite_y8.ink_20231207014000  
[2023-12-07 01:40:00] [INFO] put website.json into tmp dir successful  
[2023-12-07 01:40:00] [INFO] put openresty conf into tmp dir successful  
[2023-12-07 01:40:00] [DEBUG] tar --warning=no-file-changed --ignore-failed-read -zcf /opt/1panel/backup/website/fff.top/website_fff.top_20231207014000/fff.top.web.tar.gz  --exclude *.sock -C /opt/1panel/apps/openresty/openresty/www/sites fff.top  
[2023-12-07 01:40:00] [INFO] put web.tar.gz into tmp dir successful, now start to tar tmp dir  
[2023-12-07 01:40:00] [DEBUG] tar --warning=no-file-changed --ignore-failed-read -zcf /opt/1panel/backup/website/fff.top/website_fff.top_20231207014000.tar.gz  --exclude *.sock -C /opt/1panel/backup/website/fff.top website_fff.top_20231207014000  
[2023-12-07 01:40:00] [INFO] start to handle remove expired, retain copies: 5  
[2023-12-07 21:04:33] [INFO] init logger successfully  
[2023-12-07 21:04:33] [INFO] init db successfully  
[2023-12-07 21:04:33] [INFO] Migration run successfully  
[2023-12-07 21:04:33] [INFO] init cache successfully  
[2023-12-07 21:04:33] [INFO] init session successfully  
[2023-12-07 21:04:33] [DEBUG] synchronize system time with [pool.ntp.org] successful!  
[2023-12-07 21:04:36] [INFO] add ntp job 同步时间 successful  
[2023-12-07 21:04:36] [INFO] start cronjob entryID: 5  
[2023-12-07 21:04:36] [INFO] add website job 备份网站 successful  
[2023-12-07 21:04:36] [INFO] start cronjob entryID: 6  
[2023-12-07 21:04:36] [INFO] Starting synchronization with App Store...  
[2023-12-07 21:04:36] [INFO] listen at https://0.0.0.0:41935 [tcp4]  
[2023-12-07 21:04:38] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2023-12-07 21:04:38] [INFO] Starting synchronization of application details...  
[2023-12-07 21:05:00] [INFO] Synchronization of application details Success  
[2023-12-07 21:05:01] [INFO] Synchronization with the App Store was successful!  
2023/12/07 21:10:43 [INFO] acme: Trying to resolve account by key
2023/12/07 21:10:43 [INFO] [www.ff.ee, ff.ee] acme: Obtaining bundled SAN certificate
2023/12/07 21:10:43 [INFO] [ff.ee] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/291302899626
2023/12/07 21:10:43 [INFO] [www.ff.ee] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/291302899636
2023/12/07 21:10:43 [INFO] [ff.ee] acme: Could not find solver for: tls-alpn-01
2023/12/07 21:10:43 [INFO] [ff.ee] acme: Could not find solver for: http-01
2023/12/07 21:10:43 [INFO] [ff.ee] acme: use dns-01 solver
2023/12/07 21:10:43 [INFO] [www.ff.ee] acme: Could not find solver for: tls-alpn-01
2023/12/07 21:10:43 [INFO] [www.ff.ee] acme: Could not find solver for: http-01
2023/12/07 21:10:43 [INFO] [www.ff.ee] acme: use dns-01 solver
2023/12/07 21:10:43 [INFO] [ff.ee] acme: Preparing to solve DNS-01
2023/12/07 21:10:49 [INFO] [www.ff.ee] acme: Preparing to solve DNS-01
2023/12/07 21:10:51 [INFO] [ff.ee] acme: Cleaning DNS-01 challenge
2023/12/07 21:10:53 [WARN] [ff.ee] acme: cleaning up failed: zone lv. not found in dnspod for domain ff.ee 
2023/12/07 21:10:53 [INFO] [www.ff.ee] acme: Cleaning DNS-01 challenge
2023/12/07 21:11:06 [WARN] [www.ff.ee] acme: cleaning up failed: zone lv. not found in dnspod for domain www.ff.ee 
2023/12/07 21:11:06 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/291302899626
2023/12/07 21:11:06 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/291302899636
2023/12/07 21:11:25 [INFO] acme: Trying to resolve account by key
2023/12/07 21:11:25 [INFO] [www.ff.ee, ff.ee] acme: Obtaining bundled SAN certificate
2023/12/07 21:11:25 [INFO] [ff.ee] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/291303060046
2023/12/07 21:11:25 [INFO] [www.ff.ee] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/291303060056
2023/12/07 21:11:25 [INFO] [ff.ee] acme: Could not find solver for: tls-alpn-01
2023/12/07 21:11:25 [INFO] [ff.ee] acme: use http-01 solver
2023/12/07 21:11:25 [INFO] [www.ff.ee] acme: Could not find solver for: tls-alpn-01
2023/12/07 21:11:25 [INFO] [www.ff.ee] acme: use http-01 solver
2023/12/07 21:11:25 [INFO] [ff.ee] acme: Trying to solve HTTP-01
2023/12/07 21:11:29 [INFO] [ff.ee] The server validated our request
2023/12/07 21:11:29 [INFO] [www.ff.ee] acme: Trying to solve HTTP-01
2023/12/07 21:11:48 [INFO] [www.ff.ee] The server validated our request
2023/12/07 21:11:48 [INFO] [www.ff.ee, ff.ee] acme: Validations succeeded; requesting certificates
2023/12/07 21:11:49 [INFO] [www.ff.ee] Server responded with a certificate.
[2023-12-07 21:12:23] [INFO] init logger successfully  
[2023-12-07 21:12:23] [INFO] init db successfully  
[2023-12-07 21:12:23] [INFO] Migration run successfully  
[2023-12-07 21:12:23] [INFO] init cache successfully  
[2023-12-07 21:12:23] [INFO] init session successfully  
[2023-12-07 21:12:24] [DEBUG] synchronize system time with [pool.ntp.org] successful!  
[2023-12-07 21:12:27] [INFO] add ntp job 同步时间 successful  
[2023-12-07 21:12:27] [INFO] start cronjob entryID: 5  
[2023-12-07 21:12:27] [INFO] add website job 备份网站 successful  
[2023-12-07 21:12:27] [INFO] start cronjob entryID: 6  
[2023-12-07 21:12:27] [INFO] Starting synchronization with App Store...  
[2023-12-07 21:12:27] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2023-12-07 21:12:28] [INFO] The App Store is at the latest version  
[2023-12-07 21:18:09] [INFO] init logger successfully  
[2023-12-07 21:18:09] [INFO] init db successfully  
[2023-12-07 21:18:09] [INFO] Migration run successfully  
panic: Cannot acquire directory lock on "/opt/1panel/cache".  Another process is using this Badger database. error: resource temporarily unavailable

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/cache.Init()
	github.com/1Panel-dev/1Panel/backend/init/cache/cache.go:50 +0x17a
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:40 +0x8a
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func10(0x6e22ac0?, {0x261872e?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x17
github.com/spf13/cobra.(*Command).execute(0x6e22ac0, {0xc000050240, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x6e22ac0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x4069d9?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
	./main.go:23 +0x25
[2023-12-07 21:21:12] [INFO] init logger successfully  
[2023-12-07 21:21:19] [INFO] init db successfully  
[2023-12-07 21:21:19] [INFO] Migration run successfully  
[2023-12-07 21:21:19] [INFO] init cache successfully  
[2023-12-07 21:21:19] [INFO] init session successfully  
[2023-12-07 21:21:19] [DEBUG] synchronize system time with [pool.ntp.org] successful!  
[2023-12-07 21:21:22] [INFO] add ntp job 同步时间 successful  
[2023-12-07 21:21:22] [INFO] start cronjob entryID: 5  
[2023-12-07 21:21:22] [INFO] add website job 备份网站 successful  
[2023-12-07 21:21:22] [INFO] start cronjob entryID: 6  
[2023-12-07 21:21:22] [INFO] Starting synchronization with App Store...  
[2023-12-07 21:21:26] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2023-12-07 21:21:26] [INFO] The App Store is at the latest version  
[2023-12-07 21:27:55] [INFO] init logger successfully  
[2023-12-07 21:27:55] [INFO] init db successfully  
[2023-12-07 21:27:55] [INFO] Migration run successfully  
panic: Cannot acquire directory lock on "/opt/1panel/cache".  Another process is using this Badger database. error: resource temporarily unavailable

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/cache.Init()
	github.com/1Panel-dev/1Panel/backend/init/cache/cache.go:50 +0x17a
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:40 +0x8a
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func10(0x6e22ac0?, {0x261872e?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x17
github.com/spf13/cobra.(*Command).execute(0x6e22ac0, {0xc000050240, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x6e22ac0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x4069d9?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
	./main.go:23 +0x25
[2023-12-07 21:36:32] [INFO] init logger successfully  
[2023-12-07 21:36:38] [INFO] init db successfully  
[2023-12-07 21:36:38] [INFO] Migration run successfully  
[2023-12-07 21:36:39] [INFO] init cache successfully  
[2023-12-07 21:36:39] [INFO] init session successfully  
[2023-12-07 21:36:38] [DEBUG] synchronize system time with [pool.ntp.org] successful!  
[2023-12-07 21:36:42] [INFO] add ntp job 同步时间 successful  
[2023-12-07 21:36:42] [INFO] start cronjob entryID: 5  
[2023-12-07 21:36:42] [INFO] add website job 备份网站 successful  
[2023-12-07 21:36:42] [INFO] start cronjob entryID: 6  
[2023-12-07 21:36:42] [INFO] Starting synchronization with App Store...  
[2023-12-07 21:36:44] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2023-12-07 21:36:44] [INFO] The App Store is at the latest version
```

### 附加信息

上面日志还有申请证书失败的记录。
这种失败的情况，希望能回滚到上次的操作；
或者关闭SSL后，不要重启面板，可以换个证书再重启；
提供终端中操作命令，或者提供配置文件路径，手动改回原来配置也可以。
希望能有个临时解决办法，不想再装面板了，也没有备份。

**Comment by ssongliu** [comment]
感谢反馈，查看日志后可以确定这里大概率是缓存问题，可以尝试以下操作：
1. 1pctl stop 停止服务；
2. netstat -tunlp | grep <1Panel 端口>；如果存在进程，就给他 kill 掉；
3. 删除 /opt/1panel/cache 文件；
4. 1pctl restart 重启服务。

**Comment by 60999** [comment]
试过了，还是无法解决，访问http地址会自动跳到https地址，然后无法忽略证书错误登录，显示
“此站点的连接不安全xxx.yyy.com 发送了无效的响应。
[尝试运行 Windows 网络诊断](javascript:diagnoseErrors())。
ERR_SSL_PROTOCOL_ERROR”
使用IP也无法登录，显示拒绝连接。
请问如何更改强制https为运行http登录。
能否提供证书保存路径，配置文件，不知道删除错误的证书路径后，在配置文件中替换成后面申请的正确证书是否可以正常登录面板，或许可以试试。

**Comment by wanghe-fit2cloud** [comment]
> 试过了，还是无法解决，访问http地址会自动跳到https地址，然后无法忽略证书错误登录，显示 “此站点的连接不安全xxx.yyy.com 发送了无效的响应。 尝试运行 Windows 网络诊断。 ERR_SSL_PROTOCOL_ERROR” 使用IP也无法登录，显示拒绝连接。 请问如何更改强制https为运行http登录。 能否提供证书保存路径，配置文件，不知道删除错误的证书路径后，在配置文件中替换成后面申请的正确证书是否可以正常登录面板，或许可以试试。

可以先关闭面板 SSL，然后通过 `网站` 页面，创建反向代理网站。

**Comment by 60999** [comment]
> > 试过了，还是无法解决，访问http地址会自动跳到https地址，然后无法忽略证书错误登录，显示 “此站点的连接不安全xxx.yyy.com 发送了无效的响应。 尝试运行 Windows 网络诊断。 ERR_SSL_PROTOCOL_ERROR” 使用IP也无法登录，显示拒绝连接。 请问如何更改强制https为运行http登录。 能否提供证书保存路径，配置文件，不知道删除错误的证书路径后，在配置文件中替换成后面申请的正确证书是否可以正常登录面板，或许可以试试。
> 
> 可以先关闭面板 SSL，然后通过 `网站` 页面，创建反向代理网站。

已经在面板设置中管理了面板 SSL，现在无法登录进入面板管理。只有SSH终端能登录到系统

**Comment by wanghe-fit2cloud** [comment]
进入 SSH 终端，通过 `1pctl reset https` 命令关闭面板 SSL，参考：
https://1panel.cn/docs/installation/cli/
<img width="949" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/c0eed99c-7530-4d18-95d0-bc3d9aa61b70">

**Comment by 60999** [comment]
执行后并重启1panel依然无法登录。
并且执行 1pctl reset domain 无回显，用IP也无法登录
1pctl reset entrance 无回显，使用“1panel user-info”显示
"面板地址: http://aaa.bbb.cc:12345/ 
用户名称: aaaaaaaaa
用户密码: bbbbbbb" 之后无法登录，换IP和协议都无法登录
5个reset都试过，还是无法登录面板。

**Comment by wanghe-fit2cloud** [comment]
> 执行后并重启1panel依然无法登录。 并且执行 1pctl reset domain 无回显，用IP也无法登录 1pctl reset entrance 无回显，使用“1panel user-info”显示 "面板地址: http://aaa.bbb.cc:12345/ 用户名称: aaaaaaaaa 用户密码: bbbbbbb" 之后无法登录，换IP和协议都无法登录 5个reset都试过，还是无法登录面板。

`1pctl status` 查看一下服务状态，然后执行 `curl 127.0.0.1:12345` 命令查看一下返回结果。

**Comment by 60999** [comment]
> > 执行后并重启1panel依然无法登录。 并且执行 1pctl reset domain 无回显，用IP也无法登录 1pctl reset entrance 无回显，使用“1panel user-info”显示 "面板地址: http://aaa.bbb.cc:12345/ 用户名称: aaaaaaaaa 用户密码: bbbbbbb" 之后无法登录，换IP和协议都无法登录 5个reset都试过，还是无法登录面板。
> 
> `1pctl status` 查看一下服务状态，然后执行 `curl 127.0.0.1:12345` 命令查看一下返回结果。

# 1pctl status
● 1panel.service - 1Panel, a modern open source linux panel
     Loaded: loaded (/etc/systemd/system/1panel.service; enabled; preset: enabled)
     Active: active (running) since Sun 2023-12-10 16:22:37 CST; 1h 26min ago
   Main PID: 507294 (1panel)
      Tasks: 4 (limit: 513)
     Memory: 47.8M
        CPU: 24.990s
     CGroup: /system.slice/1panel.service
             └─507294 /usr/bin/1panel

Dec 10 16:22:41 mail.vsx.cc 1panel[507294]: [GIN-debug] GET    /api/v1/runtimes/:id      --> github.com/1Panel-dev/1Panel/backend/app/api/v1.(*BaseApi).GetRuntime-fm (11 handlers)
Dec 10 16:22:41 mail.vsx.cc 1panel[507294]: [GIN-debug] POST   /api/v1/runtimes/node/package --> github.com/1Panel-dev/1Panel/backend/app/api/v1.(*BaseApi).GetNodePackageRunScript-fm (11 handlers)
Dec 10 16:22:41 mail.vsx.cc 1panel[507294]: [GIN-debug] POST   /api/v1/runtimes/operate  --> github.com/1Panel-dev/1Panel/backend/app/api/v1.(*BaseApi).OperateRuntime-fm (11 handlers)
Dec 10 16:22:41 mail.vsx.cc 1panel[507294]: [GIN-debug] POST   /api/v1/runtimes/node/modules --> github.com/1Panel-dev/1Panel/backend/app/api/v1.(*BaseApi).GetNodeModules-fm (11 handlers)
Dec 10 16:22:41 mail.vsx.cc 1panel[507294]: [GIN-debug] POST   /api/v1/runtimes/node/modules/operate --> github.com/1Panel-dev/1Panel/backend/app/api/v1.(*BaseApi).OperateNodeModules-fm (11 handlers)
Dec 10 16:22:41 mail.vsx.cc 1panel[507294]: [GIN-debug] GET    /api/v1/process/ws        --> github.com/1Panel-dev/1Panel/backend/app/api/v1.(*BaseApi).ProcessWs-fm (11 handlers)
Dec 10 16:22:41 mail.vsx.cc 1panel[507294]: [GIN-debug] POST   /api/v1/process/stop      --> github.com/1Panel-dev/1Panel/backend/app/api/v1.(*BaseApi).StopProcess-fm (11 handlers)
Dec 10 16:22:41 mail.vsx.cc 1panel[507294]: [2023-12-10 16:22:41] [INFO] Starting synchronization with App Store...
Dec 10 16:22:41 mail.vsx.cc 1panel[507294]: [2023-12-10 16:22:41] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip
Dec 10 16:22:42 mail.vsx.cc 1panel[507294]: [2023-12-10 16:22:42] [INFO] The App Store is at the latest version


`curl 127.0.0.1:41935
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <link rel="icon" href="/assets/png/favicon-abe32304.png" />
        <meta name="robots" content="noindex,nofollow" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <title>loading...</title>
      <script type="module" crossorigin src="/assets/js/index-88aa89d8.js"></script>
      <link rel="stylesheet" href="/assets/css/index-d42199db.css">
    </head>
    <body>
        <div id="app">
            <style>
                html,
                body,
                #app {
                    width: 100%;
                    height: 100%;
                    padding: 0;
                    margin: 0;
                }
                .first-loading-wrap {
                    display: flex;
                    flex-direction: column;
                    align-items: center;
                    justify-content: center;
                    width: 100%;
                    height: 100%;
                }
                .first-loading-wrap > h1 {
                    font-size: 128px;
                }
                .first-loading-wrap .loading-wrap {
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    padding: 98px;
                }
                .dot {
                    position: relative;
                    box-sizing: border-box;
                    display: inline-block;
                    width: 32px;
                    height: 32px;
                    font-size: 32px;
                    transform: rotate(45deg);
                    animation: ant-rotate 1.2s infinite linear;
                }
                .dot i {
                    position: absolute;
                    display: block;
                    width: 14px;
                    height: 14px;
                    background-color: #1890ff;
                    border-radius: 100%;
                    opacity: 0.3;
                    transform: scale(0.75);
                    transform-origin: 50% 50%;
                    animation: ant-spin-move 1s infinite linear alternate;
                }
                .dot i:nth-child(1) {
                    top: 0;
                    left: 0;
                }
                .dot i:nth-child(2) {
                    top: 0;
                    right: 0;
                    animation-delay: 0.4s;
                }
                .dot i:nth-child(3) {
                    right: 0;
                    bottom: 0;
                    animation-delay: 0.8s;
                }
                .dot i:nth-child(4) {
                    bottom: 0;
                    left: 0;
                    animation-delay: 1.2s;
                }
                @keyframes ant-rotate {
                    to {
                        transform: rotate(405deg);
                    }
                }
                @keyframes ant-spin-move {
                    to {
                        opacity: 1;
                    }
                }
            </style>
            <div class="first-loading-wrap">
                <div class="loading-wrap">
                    <span class="dot dot-spin">
                        <i></i>
                        <i></i>
                        <i></i>
                        <i></i>
                    </span>
                </div>
            </div>
        </div>
        
    </body>
</html>`

**Comment by 60999** [comment]
curl 执行后，打开面板地址，可以访问了，但是故障原因还是很奇怪，不知道为什么会这样
