### ISSUE TITLE
[QUESTION]面板升级过程中出现错误

### ISSUE THREAD

**Issue by rakkasumi** [1Panel-dev/1Panel#3990]
### 请描述您的问题

Debian 12.2.0 内核版本6.1.0-10
1Panel版本 1.9.1 升级目标 1.9.6

日志：
panic: Cannot acquire directory lock on "/opt/1panel/cache".  Another process is using this Badger database. error: resource temporarily unavailable

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/cache.Init()
	github.com/1Panel-dev/1Panel/backend/init/cache/cache.go:50 +0x17a
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:40 +0x8a
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func10(0x6fdd220?, {0x271fb33?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x17
github.com/spf13/cobra.(*Command).execute(0x6fdd220, {0xc00010c200, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x6fdd220)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x4069d9?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
	./main.go:23 +0x25
[2024-02-27 10:59:25] [INFO] start to upgrade now...  
[2024-02-27 10:59:27] [INFO] download all file successful!  
[2024-02-27 10:59:27] [DEBUG] tar zxvfC /opt/1panel/tmp/upgrade/upgrade_20240227105925/downloads/1panel-v1.9.6-linux-amd64.tar.gz /opt/1panel/tmp/upgrade/upgrade_20240227105925/downloads  
[2024-02-27 10:59:47] [INFO] backup original data successful, now start to upgrade!  
[2024-02-27 10:59:47] [DEBUG] \cp -f /opt/1panel/tmp/upgrade/upgrade_20240227105925/downloads/1panel-v1.9.6-linux-amd64/1panel /usr/local/bin/1panel  
[2024-02-27 11:00:56] [ERROR] upgrade 1panel failed, err: cp file failed, stdout: , err: 命令执行超时！  
[2024-02-27 11:01:26] [DEBUG] \cp -f /opt/1panel/tmp/upgrade/upgrade_20240227105925/original/1Panel.db /opt/1panel/db/1Panel.db  
[2024-02-27 11:01:29] [DEBUG] \cp -f /opt/1panel/tmp/upgrade/upgrade_20240227105925/original/1panel /usr/local/bin/1panel  
[2024-02-27 11:02:06] [ERROR] rollback 1pctl failed, err: cp file failed, stdout: , err: 命令执行超时！

**Comment by wanghe-fit2cloud** [comment]
可以尝试手动重启服务器之后再来升级面板程序（重启服务器后也可以手动删除 cache 目录）

**Comment by rakkasumi** [comment]
> 可以尝试手动重启服务器之后再来升级面板程序（重启服务器后也可以手动删除 cache 目录）

重启之后手动删除了cache目录内所有文件 问题依旧

**Comment by rakkasumi** [comment]
根目录大约还剩3g，我扩容了根目录之后可以正常升级到1.10.0lts
