### ISSUE TITLE
Calibre-Web安装后为啥IP+端口能访问能登录，反向代理的域名能访问但是无法登录，密码啥的都没问题

### ISSUE THREAD

**Issue by ahhuipt** [1Panel-dev/1Panel#4527]
### 联系方式

yinhuiguo0712@foxmail.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

Calibre-Web安装后为啥IP+端口能访问能登录，反向代理的域名能访问但是无法登录，密码啥的都没问题

### 重现步骤

网站加载一直转圈

### 期待的正确结果

反向代理的Calibre-Web能正常访问

### 相关日志输出

```shell
1Panel-calibre-web-nxbt  | Failed to import PyQt module: PyQt6.QtCore with error: libQt6Core.so.6: cannot open shared object file: No such file or directory
1Panel-calibre-web-nxbt  | Traceback (most recent call last):
1Panel-calibre-web-nxbt  |   File "runpy.py", line 198, in _run_module_as_main
1Panel-calibre-web-nxbt  |   File "runpy.py", line 88, in _run_code
1Panel-calibre-web-nxbt  |   File "site.py", line 47, in <module>
1Panel-calibre-web-nxbt  |   File "site.py", line 41, in main
1Panel-calibre-web-nxbt  |   File "bypy-importer.py", line 279, in exec_module
1Panel-calibre-web-nxbt  |   File "calibre/linux.py", line 16, in <module>
1Panel-calibre-web-nxbt  |   File "bypy-importer.py", line 279, in exec_module
1Panel-calibre-web-nxbt  |   File "calibre/customize/ui.py", line 28, in <module>
1Panel-calibre-web-nxbt  |   File "bypy-importer.py", line 279, in exec_module
1Panel-calibre-web-nxbt  |   File "calibre/customize/builtins.py", line 731, in <module>
1Panel-calibre-web-nxbt  |   File "bypy-importer.py", line 279, in exec_module
1Panel-calibre-web-nxbt  |   File "calibre/devices/kobo/driver.py", line 25, in <module>
1Panel-calibre-web-nxbt  |   File "bypy-importer.py", line 279, in exec_module
1Panel-calibre-web-nxbt  |   File "calibre/devices/kobo/books.py", line 15, in <module>
1Panel-calibre-web-nxbt  |   File "bypy-importer.py", line 279, in exec_module
1Panel-calibre-web-nxbt  |   File "calibre/ebooks/metadata/book/formatter.py", line 10, in <module>
1Panel-calibre-web-nxbt  |   File "bypy-importer.py", line 279, in exec_module
1Panel-calibre-web-nxbt  |   File "calibre/utils/formatter.py", line 23, in <module>
1Panel-calibre-web-nxbt  |   File "bypy-importer.py", line 279, in exec_module
1Panel-calibre-web-nxbt  |   File "calibre/utils/formatter_functions.py", line 30, in <module>
1Panel-calibre-web-nxbt  |   File "bypy-importer.py", line 279, in exec_module
1Panel-calibre-web-nxbt  |   File "calibre/db/notes/exim.py", line 14, in <module>
1Panel-calibre-web-nxbt  |   File "bypy-importer.py", line 279, in exec_module
1Panel-calibre-web-nxbt  |   File "calibre/ebooks/oeb/transforms/rasterize.py", line 14, in <module>
1Panel-calibre-web-nxbt  | ImportError: cannot import name 'QBuffer' from 'qt.core' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)
1Panel-calibre-web-nxbt  | [custom-init] No custom files found, skipping...
1Panel-calibre-web-nxbt  | [ls.io-init] done.
```

### 附加信息

无

**Comment by wanghe-fit2cloud** [comment]
建议根据上述 Error 信息到应用官方查找一下答案。
