### ISSUE TITLE
[BUG]应用商店安装 neuxs 失败

### ISSUE THREAD

**Issue by whfay** [1Panel-dev/1Panel#455]
### 1Panel 版本

v1.0.4

### 问题描述

应用商店安装 nexus 失败。
日志：
<img width="1237" alt="图片" src="https://user-images.githubusercontent.com/29944886/228811621-fd9677f2-ac29-4a65-a554-a017233a3b0b.png">

### 重现步骤

应用商店直接安装 nexus 即可。

### 期待的正确结果

nexus 安装完成后能正常访问。

### 相关日志输出

```shell
mkdir: cannot create directory '../sonatype-work/nexus3/log': Permission denied
mkdir: cannot create directory '../sonatype-work/nexus3/tmp': Permission denied
OpenJDK 64-Bit Server VM warning: Cannot open file ../sonatype-work/nexus3/log/jvm.log due to No such file or directory

Warning:  Cannot open log file: ../sonatype-work/nexus3/log/jvm.log
Warning:  Forcing option -XX:LogFile=/tmp/jvm.log
java.io.FileNotFoundException: ../sonatype-work/nexus3/tmp/i4j_ZTDnGON8hezynsMX2ZCYAVDtQog=.lock (No such file or directory)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at com.install4j.runtime.launcher.util.SingleInstance.check(SingleInstance.java:72)
        at com.install4j.runtime.launcher.util.SingleInstance.checkForCurrentLauncher(SingleInstance.java:31)
        at com.install4j.runtime.launcher.UnixLauncher.checkSingleInstance(UnixLauncher.java:88)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:67)
```

**Comment by wanghe-fit2cloud** [comment]
v1.0.5 版本已修复。
