### ISSUE TITLE
[BUG] 从1.10.2-lts更新到1.10.3-lts时发生错误

### ISSUE THREAD

**Issue by alittlehuaji** [1Panel-dev/1Panel#4568]
### 联系方式

huajibenji@outlook.com

### 1Panel 版本

v1.10.3-lts

### 问题描述

从1.10.2-lts更新到1.10.3-lts时发生错误

### 重现步骤

检查更新->更新

### 期待的正确结果

更新到1.10.3-lts并且能正常访问

### 相关日志输出

```shell
[2024-04-18 18:51:15] [INFO] start to upgrade now...
[2024-04-18 18:51:19] [INFO] download all file successful!
[2024-04-18 18:51:19] [DEBUG] tar zxvfC /opt/1panel/tmp/upgrade/upgrade_20240418185115/downloads/1panel-v1.10.3-lts-linux-amd64.tar.gz /opt/1panel/tmp/upgrade/upgrade_20240418185115/downloads
[2024-04-18 18:51:25] [INFO] backup original data successful, now start to upgrade!
[2024-04-18 18:51:25] [DEBUG] \cp -f /opt/1panel/tmp/upgrade/upgrade_20240418185115/downloads/1panel-v1.10.3-lts-linux-amd64/1panel /usr/local/bin/1panel
[2024-04-18 18:51:26] [DEBUG] \cp -f /opt/1panel/tmp/upgrade/upgrade_20240418185115/downloads/1panel-v1.10.3-lts-linux-amd64/1pctl /usr/local/bin/1pctl
[2024-04-18 18:51:26] [DEBUG] \cp -f /opt/1panel/tmp/upgrade/upgrade_20240418185115/downloads/1panel-v1.10.3-lts-linux-amd64/1panel.service /etc/systemd/system/1panel.service
[2024-04-18 18:51:26] [INFO] upgrade successful!
[2024-04-18 18:51:26] [INFO] init logger successfully
[2024-04-18 18:51:26] [INFO] init monitor db successfully
[2024-04-18 18:51:26] [INFO] init db successfully
[2024-04-18 18:51:31] [ERROR] empty slice found
panic: empty slice found

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/migration.Init()
        github.com/1Panel-dev/1Panel/backend/init/migration/migrate.go:87 +0x9ea
github.com/1Panel-dev/1Panel/backend/server.Start()
        github.com/1Panel-dev/1Panel/backend/server/server.go:38 +0x39
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func10(0xc00106df00?, {0x3a66259?, 0x4?, 0x3a66159?})
        github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0xf
github.com/spf13/cobra.(*Command).execute(0x9447a20, {0xc000124050, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0x9447a20)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x0?)
        github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
        ./main.go:23 +0x1a
```

**Comment by ssongliu** [comment]
感谢反馈，麻烦添加一下我
<img width="230" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/73214554/b344ceca-5827-42f8-a8da-cd95d69401ad">

**Comment by orilights** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/61224409/7aefc876-124f-4eb9-985d-ec38b3f69d2f)
![image](https://github.com/1Panel-dev/1Panel/assets/61224409/7898e481-a0d8-4937-beaf-121193ba1ceb)

遇到了类似的问题，`v1.10.2-lts` 升级 `v1.10.3-lts` 后 1panel 服务无法启动，一直重启，使用 `1pctl restore` 命令回滚后再升级解决了

**Comment by cli-r** [comment]
同样遇到这个问题，尝试回退后重新升级成功

**Comment by wanghe-fit2cloud** [comment]
v1.10.4-lts 版本已发布。
