### ISSUE TITLE
[BUG] 面板更新失败

### ISSUE THREAD

**Issue by sunlewuyou** [1Panel-dev/1Panel#4834]
### 1Panel 版本

v1.10.5-lts

### 问题描述

无法更新到v1.10.6-lts (功能版本)，操作日志显示成功，但是实际是未升级成功。
![image](https://github.com/1Panel-dev/1Panel/assets/19728435/23143c55-31bb-4b5f-9354-d67cb0a2103b)

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/19728435/63381c5b-177f-4c8b-a18c-5989a7de1fc1)

### 相关日志输出

```shell
[2024-05-02 00:00:00] [INFO] The scheduled certificate update task is currently in progress ...  
[2024-05-02 00:00:00] [INFO] The scheduled certificate update task has completed  
[2024-05-02 00:00:00] [INFO] Website scheduled task in progress ...  
[2024-05-02 00:00:00] [INFO] Website scheduled task has completed  
[2024-05-02 00:00:00] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2024-05-02 00:00:00] [INFO] The App Store is at the latest version  
[2024-05-02 00:00:00] [INFO] AppStore scheduled task has completed  
[2024-05-02 00:00:12] [INFO] start to upgrade now...  
[2024-05-02 00:05:12] [ERROR] download service file failed, err: save download file [/opt/1panel/tmp/upgrade/upgrade_20240502000012/downloads/1panel-v1.10.6-lts-linux-amd64.tar.gz] error, err context deadline exceeded (Client.Timeout or context cancellation while reading body)  
[2024-05-02 18:04:41] [INFO] start to upgrade now...  
[2024-05-02 18:09:41] [ERROR] download service file failed, err: save download file [/opt/1panel/tmp/upgrade/upgrade_20240502180441/downloads/1panel-v1.10.6-lts-linux-amd64.tar.gz] error, err context deadline exceeded (Client.Timeout or context cancellation while reading body)  
[2024-05-02 18:19:04] [INFO] init logger successfully  
[2024-05-02 18:19:04] [INFO] init monitor db successfully  
[2024-05-02 18:19:04] [INFO] init db successfully  
[2024-05-02 18:19:04] [INFO] Migration run successfully  
panic: Cannot acquire directory lock on "/opt/1panel/cache".  Another process is using this Badger database. error: resource temporarily unavailable

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/cache.Init()
	github.com/1Panel-dev/1Panel/backend/init/cache/cache.go:50 +0x17f
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:42 +0x73
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func10(0xc00172ff00?, {0x3a674b9?, 0x4?, 0x3a673b9?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0xf
github.com/spf13/cobra.(*Command).execute(0x9449a20, {0xc000102070, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0x9449a20)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x0?)
	github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
	./main.go:23 +0x1a
[2024-05-02 18:19:54] [INFO] init logger successfully  
[2024-05-02 18:19:54] [INFO] init monitor db successfully  
[2024-05-02 18:19:54] [INFO] init db successfully  
[2024-05-02 18:19:54] [INFO] Migration run successfully  
[2024-05-02 18:19:54] [INFO] init cache successfully  
[2024-05-02 18:19:54] [INFO] init session successfully  
[2024-05-02 18:19:54] [DEBUG] synchronize system time with [pool.ntp.org] successful!  
[2024-05-02 18:19:57] [INFO] [xpack] init db successfully  
[2024-05-02 18:19:57] [INFO] [xpack] migration run successfully  
[2024-05-02 18:19:57] [INFO] Starting synchronization with App Store...  
[2024-05-02 18:19:57] [INFO] listen at https://0.0.0.0:37218 [tcp4]  
[2024-05-02 18:19:57] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2024-05-02 18:19:58] [INFO] The App Store is at the latest version  
[2024-05-02 18:20:17] [INFO] start to upgrade now...  
[2024-05-02 18:25:17] [ERROR] download service file failed, err: save download file [/opt/1panel/tmp/upgrade/upgrade_20240502182017/downloads/1panel-v1.10.6-lts-linux-amd64.tar.gz] error, err context deadline exceeded (Client.Timeout or context cancellation while reading body)
```

**Comment by ssongliu** [comment]
感谢反馈吗，日志显示是下载新安装包失败，可以先 `1pctl start` 重启后重试

**Comment by sunlewuyou** [comment]
好的👌经过多次尝试，莫名起码升级好了´･ᴗ･`

**Comment by ssongliu** [comment]
> ```shell
> download service file failed, err: save download file [/opt/1panel/tmp/upgrade/upgrade_20240502180441/downloads/1panel-v1.10.6-lts-linux-amd64.tar.gz] error, err context deadline exceeded (Client.Timeout or context cancellation while reading body)
> ```

download service file failed, err: save download file [/opt/1panel/tmp/upgrade/upgrade_20240502180441/downloads/1panel-v1.10.6-lts-linux-amd64.tar.gz] error, err context deadline exceeded (Client.Timeout or context cancellation while reading body)

下载的网络问题
