### ISSUE TITLE
网站相关操作全部超时[BUG]

### ISSUE THREAD

**Issue by llanc** [1Panel-dev/1Panel#6082]
### 1Panel 版本

v1.10.13-lts

### 问题描述

操作网站菜单中的新建网站（各个类别均有尝试）、删除、编辑、启动、停止 均提示操作超时。刷新页面没有任何改动。
尝试了重启1panel、重启openresty、重建openresty、升级（系统中提示升级成功但是实际版本号未变，日志中提示失败，当前版本1.21.4.3-0-focal）日志清理等均无效。查看了审计日志 只有 某个网站操作状态失败原因是超时。查看openresty日志没发现异常。

### 重现步骤

不确定我的环境之外能否复现。

### 相关日志输出

```shell
面板日志
[2024-08-09 00:00:00] [INFO] clear monitor website log  task has completed  
[2024-08-09 00:00:00] [INFO] The scheduled certificate update task is currently in progress ...  
[2024-08-09 00:00:00] [INFO] The scheduled certificate update task has completed  
[2024-08-09 00:00:00] [INFO] Website scheduled task in progress ...  
[2024-08-09 00:00:00] [INFO] Website scheduled task has completed  
[2024-08-09 01:14:00] [INFO] AppStore scheduled task in progress ...  
[2024-08-09 01:14:00] [INFO] Starting synchronization with App Store...  
[2024-08-09 01:14:00] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2024-08-09 01:14:00] [INFO] Starting synchronization of application details...  
[2024-08-09 01:14:07] [INFO] Synchronization of application details Success  
[2024-08-09 01:14:07] [INFO] Synchronization with the App Store was successful!  
[2024-08-09 01:14:07] [INFO] AppStore scheduled task has completed  
[2024-08-09 22:35:07] [INFO] 开始升级应用 openresty  
[2024-08-09 22:35:08] [DEBUG] tar --warning=no-file-changed --ignore-failed-read -zcf /opt/1panel/backup/app/openresty/openresty/openresty_20240809223508z7rc8/app.tar.gz  --exclude *.sock -C /opt/1panel/apps/openresty openresty  
[2024-08-09 22:35:12] [DEBUG] tar --warning=no-file-changed --ignore-failed-read -zcf /opt/1panel/backup/app/openresty/openresty/openresty_20240809223508z7rc8.tar.gz  --exclude *.sock -C /opt/1panel/backup/app/openresty/openresty openresty_20240809223508z7rc8  
[2024-08-09 22:35:12] [INFO] download app[OpenResty] from https://apps-assets.fit2cloud.com/stable/1panel/openresty/1.21.4.3-3-3-focal/openresty-1.21.4.3-3-3-focal.tar.gz  
[2024-08-09 22:35:17] [INFO] 开始拉取镜像 1panel/openresty:1.21.4.3-3-3-focal  
[2024-08-09 22:39:10] [INFO] 应用 openresty 升级失败 stderr: error pulling image configuration: download failed after attempts=6: dial tcp 162.125.32.2:443: i/o timeout
; stdout: 1.21.4.3-3-3-focal: Pulling from 1panel/openresty
96d54c3075c9: Already exists
7518fbccdc1e: Pulling fs layer
0cfbada594db: Pulling fs layer
f1bdd5a15332: Pulling fs layer
8c492f1a77c4: Pulling fs layer
588ee6b2819c: Pulling fs layer
a0f94abd859d: Pulling fs layer
79b132d3bf82: Pulling fs layer
bef8393c44a1: Pulling fs layer
d408b7f646b5: Pulling fs layer
e791469a6c1c: Pulling fs layer
244d99375a20: Pulling fs layer
49624928f00a: Pulling fs layer
8c492f1a77c4: Waiting
588ee6b2819c: Waiting
a0f94abd859d: Waiting
79b132d3bf82: Waiting
bef8393c44a1: Waiting
d408b7f646b5: Waiting
e791469a6c1c: Waiting
244d99375a20: Waiting
49624928f00a: Waiting
f1bdd5a15332: Retrying in 5 seconds
f1bdd5a15332: Retrying in 4 seconds
f1bdd5a15332: Retrying in 3 seconds
f1bdd5a15332: Retrying in 2 seconds
f1bdd5a15332: Retrying in 1 second
7518fbccdc1e: Retrying in 5 seconds
0cfbada594db: Retrying in 5 seconds
7518fbccdc1e: Retrying in 4 seconds
0cfbada594db: Retrying in 4 seconds
7518fbccdc1e: Retrying in 3 seconds
0cfbada594db: Retrying in 3 seconds
7518fbccdc1e: Retrying in 2 seconds
0cfbada594db: Retrying in 2 seconds
7518fbccdc1e: Retrying in 1 second
0cfbada594db: Retrying in 1 second
f1bdd5a15332: Retrying in 10 seconds
f1bdd5a15332: Retrying in 9 seconds
f1bdd5a15332: Retrying in 8 seconds
f1bdd5a15332: Retrying in 7 seconds
f1bdd5a15332: Retrying in 6 seconds
f1bdd5a15332: Retrying in 5 seconds
f1bdd5a15332: Retrying in 4 seconds
f1bdd5a15332: Retrying in 3 seconds
f1bdd5a15332: Retrying in 2 seconds
f1bdd5a15332: Retrying in 1 second
7518fbccdc1e: Retrying in 10 seconds
0cfbada594db: Retrying in 10 seconds
7518fbccdc1e: Retrying in 9 seconds
0cfbada594db: Retrying in 9 seconds
7518fbccdc1e: Retrying in 8 seconds
0cfbada594db: Retrying in 8 seconds
7518fbccdc1e: Retrying in 7 seconds
0cfbada594db: Retrying in 7 seconds
7518fbccdc1e: Retrying in 6 seconds
0cfbada594db: Retrying in 6 seconds
7518fbccdc1e: Retrying in 5 seconds
0cfbada594db: Retrying in 5 seconds
7518fbccdc1e: Retrying in 4 seconds
0cfbada594db: Retrying in 4 seconds
7518fbccdc1e: Retrying in 3 seconds
0cfbada594db: Retrying in 3 seconds
7518fbccdc1e: Retrying in 2 seconds
0cfbada594db: Retrying in 2 seconds
7518fbccdc1e: Retrying in 1 second
0cfbada594db: Retrying in 1 second
  
[2024-08-09 22:59:53] [ERROR] read bytes from log failed, err: read |0: file already closed  
[2024-08-09 23:00:30] [ERROR] read bytes from log failed, err: read |0: file already closed  
[2024-08-09 23:00:32] [ERROR] read bytes from log failed, err: read |0: file already closed  
[2024-08-09 23:05:02] [ERROR] reading webSocket message failed, err: websocket: close 1005 (no status)  
[2024-08-09 23:05:02] [DEBUG] thread of receive ws msg has exited now  
[2024-08-09 23:05:02] [INFO] websocket finished  
[2024-08-09 23:05:02] [ERROR] ssh session wait failed, err: signal: killed  
[2024-08-09 23:05:02] [DEBUG] thread of handle slave event has exited now  
[2024-08-09 23:06:23] [ERROR] send message with log to ws failed, err: write tcp4 127.0.0.1:44444->127.0.0.1:35420: write: broken pipe  
[2024-08-09 23:16:17] [INFO] init logger successfully  
[2024-08-09 23:16:17] [INFO] init monitor db successfully  
[2024-08-09 23:16:17] [INFO] init db successfully  
[2024-08-09 23:16:17] [INFO] Migration run successfully  
panic: Cannot acquire directory lock on "/opt/1panel/cache".  Another process is using this Badger database. error: resource temporarily unavailable

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/cache.Init()
	github.com/1Panel-dev/1Panel/backend/init/cache/cache.go:50 +0x1b5
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:43 +0x73
github.com/1Panel-dev/1Panel/cmd/server/cmd.init.func10(0xc0014b2e00?, {0x2ceb855?, 0x4?, 0x2ceb73d?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0xf
github.com/spf13/cobra.(*Command).execute(0x7d71640, {0xc000112000, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x7d71640)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x0?)
	github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
	./main.go:23 +0x1a
[2024-08-09 23:16:34] [INFO] init logger successfully  
[2024-08-09 23:16:34] [INFO] init monitor db successfully  
[2024-08-09 23:16:34] [INFO] init db successfully  
[2024-08-09 23:16:34] [INFO] Migration run successfully  
panic: Cannot acquire directory lock on "/opt/1panel/cache".  Another process is using this Badger database. error: resource temporarily unavailable

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/cache.Init()
	github.com/1Panel-dev/1Panel/backend/init/cache/cache.go:50 +0x1b5
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:43 +0x73
github.com/1Panel-dev/1Panel/cmd/server/cmd.init.func10(0xc0014e8e00?, {0x2ceb855?, 0x4?, 0x2ceb73d?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0xf
github.com/spf13/cobra.(*Command).execute(0x7d71640, {0xc00011e040, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x7d71640)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x0?)
	github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
	./main.go:23 +0x1a
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel_original  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/upgrade  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/system  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/backup/system  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/app  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/database  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/website  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/cache  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/original  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/resource/apps_bak  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/download  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/uploads/database/mysql  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/log/1Panel-2024-07-30.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/log/1Panel-2024-07-31.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/log/1Panel-2024-08-01.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/log/1Panel-2024-08-02.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/log/1Panel-2024-08-03.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/log/1Panel-2024-08-04.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/log/1Panel-2024-08-05.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/log/1Panel-2024-08-06.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/log/1Panel-2024-08-07.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/log/1Panel-2024-08-08.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_99AI_20240511173132.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_copilot-gpt4-service_20240204101955.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_copilot-gpt4-service_20240204102501.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_copilot-gpt4-service_20240204102708.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_copilot-gpt4-service_20240204103535.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_copilot-gpt4-service_20240204105234.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_deploy_20240102224557.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_go-proxy-bingai_20240420141038.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_lobe-chat_20240305143422.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_newapi_20240408214526.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_newapi_20240408214735.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_newapi_20240408214817.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_ninja_20240201091644.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_ninja_20240201091940.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_ninja_20240201163122.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_stirling-pdf_20240131102811.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_xcc-wxgpt_20240311165431.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_xcc-wxgpt_20240311170325.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_xcc-wxgpt_20240311170951.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_xcc-wxgpt_20240311173145.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_xcc-wxgpt_20240311174703.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_xcc-wxgpt_20240312073014.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_xcc-wxgpt_20240324151145.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_xxl-job-admin_20240218110002.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/compose_create_xxl-job-admin_20240218113214.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/image_pull_lobe-chat_20240305152618.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/image_pull_lobe-chat_latest_20240305152553.log  
[2024-08-09 23:23:30] [DEBUG] drop file /opt/1panel/tmp/docker_logs/image_pull_new-api_latest_20240724182123.log  
[2024-08-09 23:23:37] [INFO] init logger successfully  
[2024-08-09 23:23:37] [INFO] init monitor db successfully  
[2024-08-09 23:23:37] [INFO] init db successfully  
[2024-08-09 23:23:37] [INFO] Migration run successfully  
[2024-08-09 23:23:37] [INFO] init cache successfully  
[2024-08-09 23:23:37] [INFO] init session successfully  
[2024-08-09 23:23:43] [DEBUG] synchronize system time with [pool.ntp.org] successful!  
[2024-08-09 23:23:46] [INFO] [xpack] init db successfully  
[2024-08-09 23:23:46] [INFO] [xpack] migration run successfully  
[2024-08-09 23:23:46] [INFO] Starting synchronization with App Store...  
[2024-08-09 23:23:46] [INFO] listen at http://0.0.0.0:44444 [tcp4]  
[2024-08-09 23:23:51] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2024-08-09 23:23:56] [INFO] The App Store is at the latest version  
[2024-08-09 23:25:49] [ERROR] reading webSocket message failed, err: websocket: close 1005 (no status)  
[2024-08-09 23:25:49] [DEBUG] thread of receive ws msg has exited now  
[2024-08-09 23:25:49] [INFO] websocket finished  
[2024-08-09 23:25:49] [ERROR] ssh session wait failed, err: signal: killed  
[2024-08-09 23:25:49] [DEBUG] thread of handle slave event has exited now  

openresty日志
 2024/08/09 23:18:16 [warn] 8#8: no resolver defined to resolve r10.o.lencr.org while requesting certificate status, responder: r10.o.lencr.org, certificate: "/www/sites/panel.llanc.cn/ssl/fullchain.pem"
2024/08/09 23:19:13 [notice] 11#11: http file cache: /www/common/proxy/proxy_cache_dir 0.000M, bsize: 4096
2024/08/09 23:19:13 [notice] 1#1: signal 17 (SIGCHLD) received from 11
2024/08/09 23:19:13 [notice] 1#1: cache loader process 11 exited with code 0
2024/08/09 23:19:13 [notice] 1#1: signal 29 (SIGIO) received
2024/08/09 23:20:10 [notice] 1#1: signal 1 (SIGHUP) received from 18, reconfiguring
2024/08/09 23:20:10 [notice] 1#1: reconfiguring
2024/08/09 23:20:10 [notice] 1#1: using the "epoll" event method
2024/08/09 23:20:10 [notice] 1#1: start worker processes
2024/08/09 23:20:10 [notice] 1#1: start worker process 24
2024/08/09 23:20:10 [notice] 1#1: start worker process 25
2024/08/09 23:20:10 [notice] 1#1: start cache manager process 26
2024/08/09 23:20:22 [notice] 8#8: gracefully shutting down
2024/08/09 23:20:22 [notice] 9#9: gracefully shutting down
2024/08/09 23:20:22 [notice] 9#9: exiting
2024/08/09 23:20:22 [notice] 10#10: exiting
2024/08/09 23:20:22 [notice] 8#8: exiting
2024/08/09 23:20:22 [notice] 1#1: signal 17 (SIGCHLD) received from 9
2024/08/09 23:20:22 [notice] 1#1: worker process 9 exited with code 0
2024/08/09 23:20:22 [notice] 1#1: signal 29 (SIGIO) received
2024/08/09 23:20:22 [notice] 1#1: signal 17 (SIGCHLD) received from 10
2024/08/09 23:20:22 [notice] 1#1: cache manager process 10 exited with code 0
2024/08/09 23:20:22 [notice] 1#1: signal 29 (SIGIO) received
2024/08/09 23:20:22 [notice] 1#1: signal 17 (SIGCHLD) received from 8
2024/08/09 23:20:22 [notice] 1#1: worker process 8 exited with code 0
2024/08/09 23:20:22 [notice] 1#1: signal 29 (SIGIO) received
2024/08/09 23:21:08 [warn] 24#24: no resolver defined to resolve r10.o.lencr.org while requesting certificate status, responder: r10.o.lencr.org, certificate: "/www/sites/panel.llanc.cn/ssl/fullchain.pem"
180.101.245.250 - - [09/Aug/2024:23:27:00 +0800] "GET /v2/_catalog HTTP/1.1" 400 252 "-" "Go-http-client/1.1" "-"
2024/08/09 23:28:48 [error] 24#24: *162 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking, client: 178.25.242.225, server: 0.0.0.0:443
2024/08/09 23:28:52 [error] 24#24: *163 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking, client: 178.25.242.225, server: 0.0.0.0:443
2024/08/09 23:37:13 [error] 24#24: *199 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking, client: 5.164.29.116, server: 0.0.0.0:443
2024/08/09 23:38:45 [error] 24#24: *207 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking, client: 17.241.219.156, server: 0.0.0.0:443
2024/08/09 23:40:41 [error] 24#24: *216 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking, client: 104.166.80.92, server: 0.0.0.0:443
```

**Comment by llanc** [comment]
现在openresty已经升级成功，但是现在新建网站、修改配置、修改反代地址等还是全部超时，新建网站的时候我看了下目录状态，www/site/下已经建立了网站目录，config.d下也建立了网站的配置文件 但是提示超时后就被回滚删掉了

**Comment by zhengkunwang223** [comment]
网站配置文件中删除  
ssl_stapling on;
ssl_stapling_verify on;
这两行

**Comment by llanc** [comment]
如您所说，删除历史网站中所有的OCSP配置后一切正常了，我看了新创建的网站配置SSL后并没有这两项，这个地方时后来更新去掉了把，总而言之感谢你帮助。
