### ISSUE TITLE
[BUG]拖拽文件上传没反应，控制台报错

### ISSUE THREAD

**Issue by SnowyLchen** [1Panel-dev/1Panel#6206]
### 1Panel 版本

v1.10.13-lts

### 问题描述

从IDE拖拽文件上传没反应，控制台报错，idea，webstrom目前是这样的
CHROME浏览器
![image](https://github.com/user-attachments/assets/a34be535-5f19-48c7-a485-17375ad5a6c8)

### 重现步骤

![image](https://github.com/user-attachments/assets/458da322-4cec-4fe6-ac8f-12b6b99bb6d7)

### 期待的正确结果

能够上传，之前版本是好的，后来坏了

### 相关日志输出

```shell
index-BueaJKS8.js:14 TypeError: Cannot read properties of null (reading 'isFile')
    at pn (index-B6GgAEgO.js:1:17346)
    at index-B6GgAEgO.js:1:16997
    at Array.map (<anonymous>)
    at Mt (index-B6GgAEgO.js:1:16989)
    at Yr (index-BueaJKS8.js:14:1344)
    at xo (index-BueaJKS8.js:14:1415)
    at HTMLDivElement.n (index-BueaJKS8.js:18:8250)
```

**Comment by wanghe-fit2cloud** [comment]
已知问题 https://github.com/1Panel-dev/1Panel/issues/6016
我们会在近期推送更新。
