### ISSUE TITLE
[BUG] 1Panel突然无法启动，日志显示: panic: tls: failed to find any PEM data in certificate input

### ISSUE THREAD

**Issue by PatZer0** [1Panel-dev/1Panel#6782]
### 联系方式

patzer0@live.com

### 1Panel 版本

v1.10.14-lts

### 问题描述

尝试登录1Panel后台，发现无法进入，进入服务器后发现1Panel没有启动，尝试使用1pctl restart/start/stop无法启动，查看日志发现在不断重启，关键错误为
panic: tls: failed to find any PEM data in certificate input

![image](https://github.com/user-attachments/assets/aaa01b05-c7bb-4bd9-9a80-c096140d5160)
日志里面不断重复全是这个启动报错，似乎几天前就无法启动了。

### 重现步骤

重启服务器、重启1Panel

### 相关日志输出

```shell
[2024-10-19 00:00:14] [INFO] init logger successfully  
[2024-10-19 00:00:14] [INFO] init monitor db successfully  
[2024-10-19 00:00:14] [INFO] init db successfully  
[2024-10-19 00:00:14] [INFO] Migration run successfully  
[2024-10-19 00:00:14] [INFO] init cache successfully  
[2024-10-19 00:00:14] [INFO] init session successfully  
[2024-10-19 00:00:14] [DEBUG] synchronize system time with [pool.ntp.org] successful!  
[2024-10-19 00:00:17] [INFO] add website job xxxxxx successful  
[2024-10-19 00:00:17] [INFO] start cronjob entryID: 6  
[2024-10-19 00:00:17] [INFO] add app job xxxxxxxx successful  
[2024-10-19 00:00:17] [INFO] start cronjob entryID: 7  
[2024-10-19 00:00:17] [INFO] add clean job xxxxxxxxxxx successful  
[2024-10-19 00:00:17] [INFO] start cronjob entryID: 8  
[2024-10-19 00:00:17] [INFO] add snapshot job xxxxxxxxxx successful  
[2024-10-19 00:00:17] [INFO] start cronjob entryID: 9  
[2024-10-19 00:00:17] [INFO] add shell job xxxxxxxxxxxxx successful  
[2024-10-19 00:00:17] [INFO] start cronjob entryID: 10  
[2024-10-19 00:00:17] [INFO] [xpack] init db successfully  
[2024-10-19 00:00:17] [INFO] [xpack] init alert db successfully  
[2024-10-19 00:00:17] [INFO] [xpack] migration run successfully  
[2024-10-19 00:00:17] [INFO] Starting synchronization with App Store...  
panic: tls: failed to find any PEM data in certificate input

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:82 +0x8ee
github.com/1Panel-dev/1Panel/cmd/server/cmd.init.func10(0xc001332900?, {0x2d06918?, 0x4?, 0x2d06800?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0xf
github.com/spf13/cobra.(*Command).execute(0x7dae900, {0xc00019c040, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x7dae900)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x0?)
	github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
	./main.go:23 +0x1a
```

**Comment by ssongliu** [comment]
感谢反馈，是否有删除啥文件，看起来是开启了 https，但是证书文件被误删了？
可以通过 1pctl reset https 恢复

**Comment by PatZer0** [comment]
> 感谢反馈，是否有删除啥文件，看起来是开启了 https，但是证书文件被误删了？ 可以通过 1pctl reset https 恢复

1. 使用`1pctl reset https`可以恢复正常。

2. 没有删除文件，似乎是用于1panel后台的https证书过期了导致的，因为是用的LetsEncrypt的证书，三个月就会过期，但1Panel似乎只会为网站更新证书，不会为后台更新证书，只有在后台选择一次证书之后，证书才被更新（也比较麻烦），之前后台证书一直过期没有在意，后面就这样无法启动1Panel了。希望之后1Panel的SSL证书能自动使用最新的吧

**Comment by ssongliu** [comment]
麻烦加一下好友，我看看这个问题
![image](https://github.com/user-attachments/assets/297648cc-94fe-4544-bf12-aceebae786d9)

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持证书续签后自动重启 1Panel 服务，建议升级至最新版本进行尝试。
