### ISSUE TITLE
[Bug] 应用商店 metabase 启动失败

### ISSUE THREAD

**Issue by gopkg-dev** [1Panel-dev/1Panel#7127]
### 1Panel 版本

v1.10.20-lts

### 问题描述

metabase 启动失败

### 重现步骤

metabase 启动失败

### 相关日志输出

```shell
2024-11-19 11:03:08,717 ERROR liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v49.00-059::qnkhuat encountered an exception.
clojure.lang.ExceptionInfo: (conn=7298) SAVEPOINT 61ad50b2-3807-4f08-9d3d-baf726c048ec does not exist {:toucan2/context-trace [["resolve connection" {:toucan2.connection/connectable org.mariadb.jdbc.MariaDbConnection}] ["resolve connection" {:toucan2.connection/connectable nil}]]}
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:262)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:362)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:500)
	at org.mariadb.jdbc.MariaDbConnection.rollback(MariaDbConnection.java:784)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:1007)
	at metabase.db.connection$do_transaction$thunk__43489.invoke(connection.clj:146)
	at metabase.db.connection$do_transaction.invokeStatic(connection.clj:155)
	at metabase.db.connection$do_transaction.invoke(connection.clj:136)
	at metabase.db.connection$do_with_transaction_primary_method_java_sql_Connection.invokeStatic(connection.clj:189)
	at metabase.db.connection$do_with_transaction_primary_method_java_sql_Connection.invoke(connection.clj:162)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:13)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at toucan2.connection$do_with_transaction_around_method_toucan2_connection_default.invokeStatic(connection.clj:249)
	at toucan2.connection$do_with_transaction_around_method_toucan2_connection_default.invoke(connection.clj:245)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:13)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:58)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:212)
	at metabase.db.custom_migrations.UnifyTimeColumnsType$with_connection_STAR___44895.invoke(custom_migrations.clj:1031)
	at toucan2.connection$bind_current_connectable_fn$fn__22409.invoke(connection.clj:104)
	at toucan2.connection$bind_current_connectable_fn$fn__22409.invoke(connection.clj:104)
	at toucan2.jdbc.connection$do_with_connection_primary_method_java_sql_Connection.invokeStatic(connection.clj:13)
	at toucan2.jdbc.connection$do_with_connection_primary_method_java_sql_Connection.invoke(connection.clj:11)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invokeStatic(connection.clj:118)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invoke(connection.clj:106)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210)
	at toucan2.connection$do_with_connection_primary_method_.invokeStatic(connection.clj:204)
	at toucan2.connection$do_with_connection_primary_method_.invoke(connection.clj:194)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invokeStatic(connection.clj:118)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invoke(connection.clj:106)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210)
	at metabase.db.custom_migrations.UnifyTimeColumnsType.execute(custom_migrations.clj:1031)
	at liquibase.change.custom.CustomChangeWrapper.generateStatements(CustomChangeWrapper.java:170)
	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:133)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Scope.child(Scope.java:252)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108)
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
	at liquibase.command.CommandScope.execute(CommandScope.java:217)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Liquibase.runInScope(Liquibase.java:1419)
	at liquibase.Liquibase.update(Liquibase.java:234)
	at liquibase.Liquibase.update(Liquibase.java:212)
	at liquibase.Liquibase.update(Liquibase.java:194)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__45484.invoke(liquibase.clj:371)
	at metabase.db.liquibase$run_in_scope_locked$reify__45480.run(liquibase.clj:336)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at metabase.db.liquibase$run_in_scope_locked.invokeStatic(liquibase.clj:329)
	at metabase.db.liquibase$run_in_scope_locked.invoke(liquibase.clj:312)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:360)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:353)
	at metabase.db.setup$migrate_BANG_55497__55498$fn__55499.invoke(setup.clj:84)
	at metabase.db.liquibase$do_with_liquibase45414__45415$f_STAR___45416.invoke(liquibase.clj:135)
	at metabase.db.liquibase$do_with_liquibase45414__45415.invokeStatic(liquibase.clj:138)
	at metabase.db.liquibase$do_with_liquibase45414__45415.invoke(liquibase.clj:126)
	at metabase.db.setup$migrate_BANG_55497__55498.invokeStatic(setup.clj:73)
	at metabase.db.setup$migrate_BANG_55497__55498.doInvoke(setup.clj:55)
	at clojure.lang.RestFn.invoke(RestFn.java:428)
	at metabase.db.setup$run_schema_migrations_BANG_55524__55525.invokeStatic(setup.clj:149)
	at metabase.db.setup$run_schema_migrations_BANG_55524__55525.invoke(setup.clj:144)
	at metabase.db.setup$setup_db_BANG_55531__55532$fn__55535$fn__55536.invoke(setup.clj:167)
	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:238)
	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:224)
	at metabase.db.setup$setup_db_BANG_55531__55532$fn__55535.invoke(setup.clj:161)
	at metabase.db.setup$setup_db_BANG_55531__55532.invokeStatic(setup.clj:160)
	at metabase.db.setup$setup_db_BANG_55531__55532.invoke(setup.clj:153)
	at metabase.db$setup_db_BANG_$fn__55560.invoke(db.clj:86)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:81)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:68)
	at clojure.lang.RestFn.invoke(RestFn.java:424)
	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:121)
	at metabase.core$init_BANG__STAR_.invoke(core.clj:102)
	at metabase.core$init_BANG_.invokeStatic(core.clj:181)
	at metabase.core$init_BANG_.invoke(core.clj:176)
	at metabase.core$start_normally.invokeStatic(core.clj:193)
	at metabase.core$start_normally.invoke(core.clj:187)
	at metabase.core$entrypoint.invokeStatic(core.clj:226)
	at metabase.core$entrypoint.doInvoke(core.clj:220)
	at clojure.lang.RestFn.invoke(RestFn.java:400)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:135)
	at clojure.lang.Var.applyTo(Var.java:707)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.invoke(RestFn.java:400)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:135)
	at metabase.bootstrap.main(Unknown Source)
Caused by: java.sql.SQLSyntaxErrorException: (conn=7298) SAVEPOINT 61ad50b2-3807-4f08-9d3d-baf726c048ec does not exist
	... 132 more
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: SAVEPOINT 61ad50b2-3807-4f08-9d3d-baf726c048ec does not exist
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:195)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:263)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:356)
	... 128 more
Caused by: java.sql.SQLException: SAVEPOINT 61ad50b2-3807-4f08-9d3d-baf726c048ec does not exist
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1693)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1555)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1518)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:257)
	... 129 more

UPDATE SUMMARY
Run:                        466
Previously run:               0
Filtered out:                 5
-------------------------------
Total change sets:          471


FILTERED CHANGE SETS SUMMARY
DBMS mismatch:                5
```

**Comment by wanghe-fit2cloud** [comment]
根据错误信息，问题可能是由于 MySQL 数据库连接异常导致的。你可以先检查一下 MySQL 容器是否正常运行，并查看是否有相关的错误日志。

> 我在本地环境测试没有复现上述问题，应用正常启动，如图：
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/bd0e3c2e-d22b-427d-922c-d24f9da69179">
