### ISSUE TITLE
[Bug] Phantom dependency issue with @vue/runtime-core

### ISSUE THREAD

**Issue by ruibaby** [1Panel-dev/1Panel#7278]
### 1Panel Version

dev branch(d2da7e2ea5dd9a6440dd082f819cccf4109daf97)

### Problem Description

@vue/runtime-core is being used in the frontend project but not explicitly declared in package.json, creating a phantom dependency issue. This can be reproduced using pnpm, which blocks phantom dependencies by default.

```bash
More info: https://sass-lang.com/d/legacy-js-api

✓ 2201 modules transformed.
x Build failed in 17.34s
error during build:
[vite]: Rollup failed to resolve import "@vue/runtime-core" from "/Users/ryanwang/Workspace/github/ruibaby/1Panel/frontend/src/views/host/file-management/index.vue?vue&type=script&setup=true&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///Users/ryanwang/Workspace/github/ruibaby/1Panel/frontend/node_modules/.pnpm/vite@5.4.11_@types+node@20.17.9_sass@1.82.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65589:17)
    at onRollupWarning (file:///Users/ryanwang/Workspace/github/ruibaby/1Panel/frontend/node_modules/.pnpm/vite@5.4.11_@types+node@20.17.9_sass@1.82.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65621:5)
    at onwarn (file:///Users/ryanwang/Workspace/github/ruibaby/1Panel/frontend/node_modules/.pnpm/vite@5.4.11_@types+node@20.17.9_sass@1.82.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65284:7)
    at file:///Users/ryanwang/Workspace/github/ruibaby/1Panel/frontend/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:19475:13
    at Object.logger [as onLog] (file:///Users/ryanwang/Workspace/github/ruibaby/1Panel/frontend/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:21201:9)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/ryanwang/Workspace/github/ruibaby/1Panel/frontend/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:20090:26)
    at file:///Users/ryanwang/Workspace/github/ruibaby/1Panel/frontend/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:20048:26
 ELIFECYCLE  Command failed with exit code 1.
```

### Steps to Reproduce

1. npx pnpm@9 install
2. npx pnpm@9 build:dev

**Comment by ruibaby** [comment]
i will submit a PR to fix this issue

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
