### ISSUE TITLE
[Bug] App store failed to install Logto

### ISSUE THREAD

**Issue by Oniokey** [1Panel-dev/1Panel#7282]
### 1Panel Version

v1.10.21-lts

### Problem Description

在应用商店中安装 Logto 时，容器出错退出。

### Steps to Reproduce

1. 在应用商店中安装 Logto
2. 使用阿里云远程数据库 PostgreSQL

### Related log output

```shell
[2KLogto  | 
[2KLogto  | > cli
[2KLogto  | > logto db seed --swe
[2KLogto  | 
[2KLogto  | - Create tables
[2KLogto  | info ✖ Create tables
[2KLogto  | error error: permission denied to create role
[2KLogto  |     at /etc/logto/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526:17
[2KLogto  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2KLogto  |     at async file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/query.js:4:24
[2KLogto  |     at async executeQuery (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/routines/executeQuery.js:130:26)
[2KLogto  |     at async query (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/query.js:3:12)
[2KLogto  |     at async runLifecycleQuery (file:///etc/logto/packages/cli/lib/commands/database/seed/tables.js:53:13)
[2KLogto  |     at async createTables (file:///etc/logto/packages/cli/lib/commands/database/seed/tables.js:70:5)
[2KLogto  |     at async oraPromise (file:///etc/logto/packages/cli/lib/utils.js:72:24)
[2KLogto  |     at async file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:15:27
[2KLogto  |     at async execTransaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction.js:16:24)
[2KLogto  |     at async transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction.js:74:16)
[2KLogto  |     at async createConnection (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/factories/createConnection.js:108:18)
[2KLogto  |     at async Object.transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/binders/bindPool.js:108:20)
[2KLogto  |     at async seedByPool (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:8:5)
[2KLogto  |     at async Object.handler (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:77:13) {
[2KLogto  |   length: 145,
[2KLogto  |   severity: 'ERROR',
[2KLogto  |   code: '42501',
[2KLogto  |   detail: 'Only roles with the CREATEROLE attribute may create roles.',
[2KLogto  |   hint: undefined,
[2KLogto  |   position: undefined,
[2KLogto  |   internalPosition: undefined,
[2KLogto  |   internalQuery: undefined,
[2KLogto  |   where: undefined,
[2KLogto  |   schema: undefined,
[2KLogto  |   table: undefined,
[2KLogto  |   column: undefined,
[2KLogto  |   dataType: undefined,
[2KLogto  |   constraint: undefined,
[2KLogto  |   file: 'user.c',
[2KLogto  |   line: '355',
[2KLogto  |   routine: 'CreateRole',
[2KLogto  |   notices: []
[2KLogto  | }
[2KLogto  | error Error ocurred during seeding your database.
[2KLogto  | 
[2KLogto  |   Nothing has changed since the seeding process was in a transaction.
[2KLogto  |   Try to fix the error and seed again.
[2KLogto  | error: permission denied to create role
[2KLogto  |     at /etc/logto/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526:17
[2KLogto  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2KLogto  |     at async file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/query.js:4:24
[2KLogto  |     at async executeQuery (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/routines/executeQuery.js:130:26)
[2KLogto  |     at async query (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/query.js:3:12)
[2KLogto  |     at async runLifecycleQuery (file:///etc/logto/packages/cli/lib/commands/database/seed/tables.js:53:13)
[2KLogto  |     at async createTables (file:///etc/logto/packages/cli/lib/commands/database/seed/tables.js:70:5)
[2KLogto  |     at async oraPromise (file:///etc/logto/packages/cli/lib/utils.js:72:24)
[2KLogto  |     at async file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:15:27
[2KLogto  |     at async execTransaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction.js:16:24)
[2KLogto  |     at async transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction.js:74:16)
[2KLogto  |     at async createConnection (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/factories/createConnection.js:108:18)
[2KLogto  |     at async Object.transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/binders/bindPool.js:108:20)
[2KLogto  |     at async seedByPool (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:8:5)
[2KLogto  |     at async Object.handler (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:77:13) {
[2KLogto  |   length: 145,
[2KLogto  |   severity: 'ERROR',
[2KLogto  |   code: '42501',
[2KLogto  |   detail: 'Only roles with the CREATEROLE attribute may create roles.',
[2KLogto  |   hint: undefined,
[2KLogto  |   position: undefined,
[2KLogto  |   internalPosition: undefined,
[2KLogto  |   internalQuery: undefined,
[2KLogto  |   where: undefined,
[2KLogto  |   schema: undefined,
[2KLogto  |   table: undefined,
[2KLogto  |   column: undefined,
[2KLogto  |   dataType: undefined,
[2KLogto  |   constraint: undefined,
[2KLogto  |   file: 'user.c',
[2KLogto  |   line: '355',
[2KLogto  |   routine: 'CreateRole',
[2KLogto  |   notices: []
[2KLogto  | }
[2KLogto  | 
[2KLogto  | Specify --help for available options
Logto exited with code 1
```

### Additional Information

安装时的配置（部分）：

|项目|值|
|:---:|:---:|
|数据库名|logto|
|数据库用户|logto|
|数据库用户密码|logto_rYKzs5|
|Logto 监听的端口|3000|
|Logto 管理控制台端口|3001|

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Contact Information

buy north and south

### 1Panel Version

v1.10.21-lts

### Problem Description

When installing Logto in the app store, the container exits with an error.

### Steps to Reproduce

1. Install Logto in the app store
2. Use Alibaba Cloud remote database PostgreSQL

### The expected correct result

_No response_

### Related log output

```shell
[2KLogto |
[2KLogto | > cli
[2KLogto | > logto db seed --swe
[2KLogto |
[2KLogto | - Create tables
[2KLogto | info ✖ Create tables
[2KLogto | error error: permission denied to create role
[2KLogto | at /etc/logto/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526:17
[2KLogto | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2KLogto | at async file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/query.js: 4:24
[2KLogto | at async executeQuery (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/routines/executeQuery. js:130:26)
[2KLogto | at async query (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/query. js:3:12)
[2KLogto | at async runLifecycleQuery (file:///etc/logto/packages/cli/lib/commands/database/seed/tables.js:53:13)
[2KLogto | at async createTables (file:///etc/logto/packages/cli/lib/commands/database/seed/tables.js:70:5)
[2KLogto | at async oraPromise (file:///etc/logto/packages/cli/lib/utils.js:72:24)
[2KLogto | at async file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:15:27
[2KLogto | at async execTransaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction. js:16:24)
[2KLogto | at async transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction. js:74:16)
[2KLogto | at async createConnection (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/factories/createConnection. js:108:18)
[2KLogto | at async Object.transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/binders/ bindPool.js:108:20)
[2KLogto | at async seedByPool (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:8:5)
[2KLogto | at async Object.handler (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:77:13) {
[2KLogto | length: 145,
[2KLogto | severity: 'ERROR',
[2KLogto | code: '42501',
[2KLogto | detail: 'Only roles with the CREATEROLE attribute may create roles.',
[2KLogto | hint: undefined,
[2KLogto | position: undefined,
[2KLogto | internalPosition: undefined,
[2KLogto | internalQuery: undefined,
[2KLogto | where: undefined,
[2KLogto | schema: undefined,
[2KLogto | table: undefined,
[2KLogto | column: undefined,
[2KLogto | dataType: undefined,
[2KLogto | constraint: undefined,
[2KLogto | file: 'user.c',
[2KLogto | line: '355',
[2KLogto | routine: 'CreateRole',
[2KLogto | notices: []
[2KLogto | }
[2KLogto | error Error ocurred during seeding your database.
[2KLogto |
[2KLogto | Nothing has changed since the seeding process was in a transaction.
[2KLogto | Try to fix the error and seed again.
[2KLogto | error: permission denied to create role
[2KLogto | at /etc/logto/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526:17
[2KLogto | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2KLogto | at async file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/query.js: 4:24
[2KLogto | at async executeQuery (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/routines/executeQuery. js:130:26)
[2KLogto | at async query (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/query. js:3:12)
[2KLogto | at async runLifecycleQuery (file:///etc/logto/packages/cli/lib/commands/database/seed/tables.js:53:13)
[2KLogto | at async createTables (file:///etc/logto/packages/cli/lib/commands/database/seed/tables.js:70:5)
[2KLogto | at async oraPromise (file:///etc/logto/packages/cli/lib/utils.js:72:24)
[2KLogto | at async file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:15:27
[2KLogto | at async execTransaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction. js:16:24)
[2KLogto | at async transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/connectionMethods/transaction. js:74:16)
[2KLogto | at async createConnection (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/factories/createConnection. js:108:18)
[2KLogto | at async Object.transaction (file:///etc/logto/node_modules/.pnpm/@silverhand+slonik@31.0.0-beta.2/node_modules/@silverhand/slonik/dist/src/binders/ bindPool.js:108:20)
[2KLogto | at async seedByPool (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:8:5)
[2KLogto | at async Object.handler (file:///etc/logto/packages/cli/lib/commands/database/seed/index.js:77:13) {
[2KLogto | length: 145,
[2KLogto | severity: 'ERROR',
[2KLogto | code: '42501',
[2KLogto | detail: 'Only roles with the CREATEROLE attribute may create roles.',
[2KLogto | hint: undefined,
[2KLogto | position: undefined,
[2KLogto | internalPosition: undefined,
[2KLogto | internalQuery: undefined,
[2KLogto | where: undefined,
[2KLogto | schema: undefined,
[2KLogto | table: undefined,
[2KLogto | column: undefined,
[2KLogto | dataType: undefined,
[2KLogto | constraint: undefined,
[2KLogto | file: 'user.c',
[2KLogto | line: '355',
[2KLogto | routine: 'CreateRole',
[2KLogto | notices: []
[2KLogto | }
[2KLogto |
[2KLogto | Specify --help for available options
Logto exited with code 1
```


### Additional Information

Configuration during installation (part):

|item|value|
|:---:|:---:|
|Database name|logto|
|Database User|logto|
|Database user password|logto_rYKzs5|
|Logto listening port|3000|
|Logto Management Console Port|3001|

**Comment by wanghe-fit2cloud** [comment]
Thanks for your feedback. I couldn’t reproduce the issue locally. For the error logs, consider reporting them to Logto’s issue tracker for a solution.
